/*
 * File: app/view/BoxInfo.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPAD.view.appworkspace.Contract.BoxInfo', {
    extend: 'Ext.Container',
    id:'boxinfo',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate',
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '箱头进度信息',
                items: [
                    {
                    	id:'boxinfo_FH',
                        xtype: 'button',
                        ui: 'back',
                        text: '返回'
                    }
                ]
            },
            {
                xtype: 'list',
                height: '100%',
                id:'boxinfo_list',
                store:'ContractStore_erp_BoxInfo',
                itemTpl: [
                    '<table align="center" border=0 height=25 width=100% style="color:#666" class="textf">'+
                     '<tr>'+
                     '<td width=60%>箱头编号:{ELVBOX_NAME}</td>'+
                     '<td width=40%>箱头说明:{ELVBOX_DESC}</td>'+
                     '</tr>'+
                     '<tr>'+
                     '<td width=50%>箱头制造地:{MAKE_ORGANIZATION_NAME}</td>'+
                     '<td width=50%>拉动方式:{DELIVERY_TYPE_MEANING}</td>'+
                     '</tr>'+
//                     '<tr>'+
//                     '<td width=50%>在仓库:{SUBINV_NAME}</td>'+
//                     '</tr>'+
                    '</table>',
                ],
                onItemDisclosure: true
            }
        ]
    }

});