/*
 * File: app/view/InstallatoinTasksAssignPanelPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPDA.view.install.installtask.InstallatoinTasksAssignPanelPanel', {
    extend: 'Ext.Panel',
    //extend:'HelcPDA.controller.ApplicationController',
    id:'InstallatoinTasksAssignPanelPanel_id',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Select'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '安装任务转派',//从指定按钮进入
                items: [
                    {
                        xtype: 'button',
                        text: '返回',
                        ui:'back',
                        id:'InstallatoinTasksAssignPanelPanel_id_FH_BUTTON',
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                flex: 2,
                scrollable: false,
                items: [
                        {
                            xtype: 'fieldset',
                            items: [
                                {
                                    xtype: 'selectfield',
                                    id:'InstallatoinTasksAssignSelectfield_id',
                                    label: '服务商',
                                    labelWidth: '30%',
                                    placeHolder:'请选择',
                                    displayField:'VENDOR_NAME',	
                                    valueField:'VENDOR_ID',
                                    options: [
                                    ],
                                    usePicker: 'auto',
                                },
                                {
                                    xtype: 'textfield',
                                    id:'fuws_id',
                                    label: '关键字',
                                    labelWidth: '30%',
                                    placeHolder: '服务商查询',
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            items: [
                                {
                                    xtype: 'selectfield',
                                    id:'InstallatoinTasksAssignSelectfield_id2',
                                    label: '人员',
                                    labelWidth: '30%',
                                    placeHolder:'请选择',
                                    displayField:'PERSON_NAME',
                                    valueField:'INST_PERSON_ID',
                                    style:'color:#000;',
                                    options: [
                                    ],
                                    usePicker: 'auto'
                            	},{
                                },
                                {
                                    xtype: 'textfield',
                                    id:'ren_id',
                                    label: '关键字',
                                    labelWidth: '30%',
                                    placeHolder: '人员查询',
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            items: [
                                    {
                                        xtype: 'hiddenfield',
                                        name:'hidden',
                                        id:'Hidden_id',
                                        value:'111'
                                    },
                                    {
                                        xtype: 'container',
                                        margin: '10 15',
                                        items: [
                                            {
                                                xtype: 'button',
                                                margin: '',
                                                id:'sure_Id',
                                                text: '确认'
                                            }
                                        ]
                                   }
                            ]
                        },
                ]
            }
        ]
    }

});