/*
 * File: app/view/MyPanel37.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPDA.view.install.installtask.zhengfujian', {
    extend: 'Ext.Panel',
    id:'zhengfujian_id',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '政府检任务',
                items: [
                    {
                        xtype: 'button',
                        ui:'back',
                        text: '返回',
                        id:'zhengfujian_id_FH_BUTTON',
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },{
            	xtype:'hiddenfield',
            	id:'zhengfuHidden_id',
            	value:''
            },{
            	xtype:'textfield',
            	id:'zhengfucount_id',
            	value:'总台数:',
                readOnly:true,	
            },
            {
                xtype: 'list',
                id:'zhengfujianList_id',
                data: [
                    
                ],
                height: '100%',
                itemId: 'mylist20',
                itemTpl: [
                    '<table border=0 width=100% style="color:#666">',
                    '  <tr>',
                    //font-size:18px;
                    '    <td style="color:#000;">{ENGCONTRACT_NUMBER}/{sum}</td>',
                    '  </tr>',
                    '  <tr>',
                    '      <td>项目名称:{PROJECT_NAME}</td>',
                    '  </tr>',
                    '</table>'
                ],
                onItemDisclosure: true,
                store:'ZhengFujianStore'
            }
        ]
    }

});