/*
 * File: app/view/CompetitorAnalysis.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcAgent.view.OpportunityManagement.Project_New.CompetitorAnalysis', {
    extend: 'Ext.form.Panel',
    id:'competitoranalysis_new_id',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Toggle'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '竞争对手分析',
                cls:'textf',
                items: [
                    {
                    	id:'competitoranalysis_new_id_FH',
                        xtype: 'button',
                        ui: 'back',
                        text: '返回'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                    	id:'competitoranalysis_new_id_BC',
                        xtype: 'button',
                        text: ' 保存'
                    },{
                    	id:'competitorOpportunity',
                    	xtype:'hiddenfield',
                    },{
                    	id:'competitorId',
                    	xtype:'hiddenfield'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: '竞争对手分析',
                cls:'textf',
                items: [
                    {
                    	id:'competitorName',
                        xtype: 'selectfield',
                        label: '品牌',
                        placeHolder: '请选择品牌'
                    },{
                    	id:'competitorProduct',
                    	xtype:'textfield',
                    	label:'产品信息'
                    	
                    },
                    {
                    	id:'competitordDeliveryDate',
                        xtype: 'textfield',
                        label: '交货期',
                        width:'100%',
                        placeHolder: '请输入交货期',
                        listeners:{
                        	focus:function(){
                        			initDate1('competitordDeliveryDate','预计签约时间');
                        	}
                        }
                        	
                    },
                    {
                    	id:'competitordPayAmount',
                        xtype: 'numberfield',
                        label: '合同金额',
                        placeHolder: '请输入合同金额'
                    },{
                    	id:'competitordCurrency',
                    	xtype:'selectfield',
                    	label:'币种',
                    	options:[
                    	      {text:'人民币',value:'人民币'}   
                    	]
                    },
                    {
                    	id:'competitordQuantity',
                        xtype: 'numberfield',
                        label: '台量',
                        placeHolder: '请输入台量'
                    },
                    /*{
                        xtype: 'togglefield',
                        label: '中标品牌'
                    },*/{
                    	id:'competitordComments',
                    	xtype:'textareafield',
                    	label:'备注',
                    	
                    }
                ]
            }
        ]
    }

});