/*
 * File: app/view/Agents/ClueSearchAgent.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPAD.view.OpportunityManagement.Agents.ClueSearchAgent', {
    extend: 'Ext.form.Panel',
    id:'clueSearchAgent',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.FieldSet',
        'Ext.field.Select'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '线索查询',
                cls:'textf',
                items: [
                    {
                    	id:'clueSearchAgentBack',
                        xtype: 'button',
                        ui: 'back',
                        text:'返回',
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                    	id:'clueSearchAgentLookUp',
                        xtype: 'button',
                        text: '查找'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                cls:'textf',
                items: [
                    {
                    	id:'clueSearchStatus',
                        xtype: 'selectfield',
                        label: '报备状态',
                        labelWidth: 100,
                        options: [
                            {text:'新建',value:'新建'},
                            {text:'审批中',value:'审批中'},
                            {text:'已取消',value:'已取消'},
                            {text:'报备成功',value:'报备成功'},
                            {text:'已终止',value:'已终止'},
                            {text:'报备失败',value:'报备失败'},
                            
                        ]
                    },
                    {
                    	id:'clueSearchNumber',
                        xtype: 'textfield',
                        label: '报备编号',
                        labelWidth: 100
                    },
                    {
                    	id:'projectSearchName',
                        xtype: 'textfield',
                        label: '项目名称',
                        labelWidth: 100
                    }
                ]
            }
        ]
    }

});