Ext.define('HelcOA.model.startTheProcess.startTheProcessModel',{
	extend:'Ext.data.Model',
	config:{
		fields:[
		        'appacronym','appid','appname','bpdid','cfgid','id1',
		        'snapshotcreatedon','snapshotid','snapshotname',
		        'bpdname']
	}
});