/*
 * File: app/view/MyContainer18.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcBPM.view.install.INS_Approve', {
    extend: 'Ext.Container',
    id:'INS_Approve',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.TextArea',
        'Ext.Spacer'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '安装委托合同审批',
                items: [
                    {
                        xtype: 'button',
                        id:'btn_INSapprove_back',
                        ui: 'back',
                        text: '返回'
                    },
                    {
                    	xtype: 'spacer'
                    },
//                    {
//                        xtype: 'button',
//                        id:'btn_INSapprove_refresh',
//                        text: '刷新'
//                    }
                ]
            },
            {
                xtype: 'tabpanel',
                height: '100%',
                id: 'tp_detailPanel',
                items: [
                    {
                        xtype: 'formpanel',
                        id: 'gc_totalView',
                        title: '工程合同总览',
                        items: [
                            {
                                xtype: 'fieldset',
                                title: '项目情况',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'GchtNo',
                                        style: 'float: left',
                                        width: '33%',
                                        labelWidth:120,
                                        label: '工程合同号:',
                                        readOnly: true,
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'HtNum',
                                        style: 'float: left',
                                        width: '33%',
                                        labelWidth:120,
                                        label: '合同台数:',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'QtcbPercent',
                                        style: 'float: left',
                                        width: '33%',
                                        labelWidth:160,
                                        label: '其他成本费率(%):',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'Yfs',
                                        style: 'float: left',
                                        width: '33%',
                                        labelWidth:80,
                                        label: '营分司:',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ClientName',
                                        style: 'float: left',
                                        width: '33%',
                                        labelWidth:60,
                                        label: '客户:',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'HeaderDkh',
                                        style: 'float: left',
                                        width: '33%',
                                        labelWidth:80,
                                        label: '大客户:',
                                        readOnly: true
                                    }
                                  ]
                            	},
                            	{
                                    xtype: 'fieldset',
                                    title: '工程合同签约情况',
                                    items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'GchtAmt',
                                        style: 'float: left',
                                        labelWidth:200,
                                        width: '33%',
                                        label: '①工程合同价额(元):',
//                                        value:'45,500.00',
                                        labelWrap : true,
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'GchtBzAmt',
                                        style: 'float: left',
                                        labelWidth:220,
                                        width: '33%',
                                        label: '②工程合同标准金额(元):',
//                                        value:'45,091.00',
                                        labelWrap : true,
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'QyPercent',
                                        style: 'float: left',
                                        labelWidth:200,
                                        width: '33%',
                                        label: '①/②签约比(%):',
//                                        value:'91%',
                                        labelWrap : true,
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                html: '<table id="table_gcht" style=\'text-align:center;\' align=\'center\' width=\'100%\' border=\'1\' cellpadding=\'0\' cellspacing="0">' +
                                		'<tr>' +
                                		'<td></td>' +
                                		'<td class="tbl_nobr_one">款项</td>' +
                                		'<td class="tbl_nobr_one">委托金额</br>（不含税）</td>' +
	                            		'<td class="tbl_nobr_one">变更金额</br>（不含税）</td>' +
	                            		'<td class="tbl_nobr_one">结算金额</br>（不含税）</td>' +
	                            		'<td class="tbl_nobr_one">标准金额</br>（不含税）</td>' +
	                            		'<td class="tbl_nobr_one">标准比</br>（%）</td>' +
	                            		'<td class="tbl_nobr_one">结算金额 </br>（含税）</td>' +
	                            		'<td class="tbl_nobr_one">占签约合同</br>额比率（%）</td>' +
	                            		'<td class="tbl_nobr_one">预估安装</br>成本率（%）</td>' +
                                		'</tr>' +
                                		'</table>',
                                margin: '',
                                padding: 5,
                                title: '工程合同委托情况'
                            },
             
                        ]
                    },
                    {
                    xtype: 'formpanel',
                    id: 'wt_totalView',
                    title: '委托合同审批',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: '项目情况',
                            items: [    
                                    {
                                        xtype: 'textfield',
                                        id: 'WthtNo',
                                        style: 'float: left',
                                        width: '50%',
                                        labelWidth:160,
                                        label: '委托合同号:',
//                                        value:'BA0118A00001',
                                        readOnly: true,
                                        
                                    },{
                                        xtype: 'textfield',
                                        id: 'WtYfs',
                                        style: 'float: left',
                                        width: '50%',
                                        labelWidth:160,
                                        label: '营分司:',
//                                        value:'广分司 ',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'WtGchtNo',
                                        style: 'float: left',
                                        width: '50%',
                                        labelWidth:160,
                                        label: '工程合同号:',
//                                        value:'AH0651846',
                                        readOnly: true,
                                        
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'WthtType',
                                        style: 'float: left',
                                        width: '50%',
                                        labelWidth:160,
                                        label: '委托合同类型:',
//                                        value:'安装综合委托合同',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'WtClientName',
                                        style: 'float: left',
                                        width: '50%',
                                        labelWidth:160,
                                        label: '客户:',
//                                        value:'广州荣雅投资有限公司 ',
                                        readOnly: true
                                    },
                                    
                                {
                                    xtype: 'textfield',
                                    id: 'Gcfws',
                                    style: 'float: left',
                                    width: '50%',
                                    labelWidth:160,
                                    label: '工程服务商:',
//                                    value:'开平华工程有限公司 ',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'WtspVersion',
                                    style: 'float: left',
                                    width: '50%',
                                    labelWidth:160,
                                    label: '委托合同申请版本:',
//                                    value:'1',
                                    readOnly: true
                                },                               
                                
                              ]
                        	},
                        	{
                                xtype: 'fieldset',
                                title: '',
                                items: [
                                {
                                    xtype: 'textfield',
                                    id: 'WtGchtAmt',
                                    style: 'float: left',
                                    labelWidth:200,
                                    width: '33%',
                                    label: '①工程合同价额(元):',
//                                    value:'45,500.00',
                                    labelWrap : true,
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'WtGchtBzAmt',
                                    style: 'float: left',
                                    labelWidth:220,
                                    width: '33%',
                                    label: '②工程合同标准金额(元):',
//                                    value:'45,091.00',
                                    labelWrap : true,
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'WtQyPercent',
                                    style: 'float: left',
                                    labelWidth:200,
                                    width: '33%',
                                    label: '①/②签约比(%):',
//                                    value:'91%',
                                    labelWrap : true,
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'LswtAmt',
                                    style: 'float: left',
                                    labelWidth:200,
                                    width: '33%',
//                                  label: '历史委托金额(元):',
                                    label: '③已审批金额(元):',
//                                    value:'0.00',
                                    labelWrap : true,
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'LswtBzAmt',
                                    style: 'float: left',
                                    labelWidth:220,
                                    width: '33%',
//                                  label: '历史委托标准金额(元) :',
                                    label: '④已审批标准金额(元):',
//                                    value:'0.00',
                                    labelWrap : true,
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'LsQyPercent',
                                    style: 'float: left',
                                    labelWidth:200,
                                    width: '33%',
//                                  label: '历史委托/标准(%):',
                                    label: '③/④标准比(%):',
//                                    value:'0',
                                    labelWrap : true,
                                    readOnly: true
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            html: '<table id="table_wtgcht" style=\'text-align:center;\' align=\'center\' width=\'100%\' border=\'1\' cellpadding=\'0\' cellspacing="0">' +
                            		'<tr>' +
                            		'<td></td>' +
                            		'<td class="tbl_nobr_one">款项</td>' +
                            		'<td class="tbl_nobr_one">委托金额</br>（不含税）</td>' +
                            		'<td class="tbl_nobr_one">变更金额</br>（不含税）</td>' +
                            		'<td class="tbl_nobr_one">结算金额</br>（不含税）</td>' +
                            		'<td class="tbl_nobr_one">标准金额</br>（不含税）</td>' +
                            		'<td class="tbl_nobr_one">标准比 </br>（%）</td>' +
                            		'<td class="tbl_nobr_one">结算金额 </br>（含税）</td>' +
                            		'<td class="tbl_nobr_one">占签约合同</br>额比率（%）</td>' +
                            		'<td class="tbl_nobr_one">预估安装</br>成本率（%）</td>' +
                            		'</tr>' +
                            		'</table>',
                            margin: '',
                            padding: 5,
                            title: ''
                        },
                        {
                        xtype: 'fieldset',
                        title: '',
                        items: [
//-----------------------------------------------  
                        {
                            xtype: 'textfield',
                            id: 'LsTgSpWtAmt',
                            style: 'float: left',
                            labelWidth:130,
                            width: '23%',
                            label: '历史委托金额:',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'CurrentWtAmt',
                            style: 'float: left',
                            labelWidth:130,
                            width: '30%',
                            label: '当前委托金额:',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: '',
                            style: 'float: left',
                            labelWidth:140,
                            width: '22%',
                            label: '空白',
                            labelCls:'font_white',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: '',
                            style: 'float: left',
                            labelWidth:140,
                            width: '25%',
                            label: '空白',
                            labelCls:'font_white',
                            labelWrap : false,
                            readOnly: true
                        },
//-----------------------------------------------  
                        {
                            xtype: 'textfield',
                            id: 'Wt_spje',
                            style: 'float: left',
                            labelWidth:100,
                            width: '23%',
                            label: '审批金额:',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'Wt_spbzje',
                            style: 'float: left',
                            labelWidth:130,
                            width: '30%',
                            label: '审批标准金额:',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'Wt_spz',
                            style: 'float: left',
                            labelWidth:120,
                            width: '22%',
                            label: '审批值(%):',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'ZzSpcc',
                            style: 'float: left',
                            labelWidth:110,
                            width: '25%',
                            label: '最终审批层:',
                            labelWrap : true,
                            readOnly: true
                        },
//-----------------------------------------------                        
                        {
                            xtype: 'textfield',
                            id: 'Wt_zjje',
                            style: 'float: left',
                            labelWidth:100,
                            width: '23%',
                            label: '增减金额 :',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'Wt_pfhtje',
                            style: 'float: left',
                            labelWidth:180,
                            width: '30%',
                            label: '批复合同金额不含税:',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'Wt_pfcbl',
                            style: 'float: left',
                            labelWidth:140,
                            width: '22%',
                            label: '批复成本率(%):',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'PfYgCbPercent',
                            style: 'float: left',
                            labelWidth:180,
                            width: '25%',
                            label: '批复预估成本率(%):',
                            labelWrap : true,
                            readOnly: true
                        },
//----------------------------------------------- 
                        {
                            xtype: 'textfield',
                            id: 'CurrentWthtNum',
                            style: 'float: left',
                            labelWidth:180,
                            width: '33%',
                            label: '本次委托合同台数:',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'SbKcFwfXtPercent',
                            style: 'float: left',
                            labelWidth:260,
                            width: '33%',
                            label: '设备扣除服务费后下浮率(%):',
                            labelWrap : true,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'Wt_pfz',
                            style: 'float: left',
                            inputCls:'input-backgroundcolor-FFC0CB',
                            labelWidth:120,
                            width: '33%',
                            label: '批复值(%):',
                            labelWrap : true,
                            placeHolder: '请输入...'
                        },
						{
                            xtype: 'autoTextArea',
                            id: 'Wt_note',
                            style: 'float: left',
                            inputCls:'input-backgroundcolor-FFF8DC',
                            width: '100%',
                            labelWidth:120,
                            label: '审批意见:',
                            value: '同意！',
                            placeHolder: '请输入...'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    html: '<table id="table_attachment" style=\'text-align:center;\' align=\'center\' width=\'100%\' border=\'1\' cellpadding=\'0\' cellspacing="0">' +
                    		'<tr>' +
                    		'<td class="tbl_nobr_one">文件名</td>' +
                    		'<td class="tbl_nobr_one">文件大小</td>' +
                    		'<td class="tbl_nobr_one">创建时间</td>' +
                    		'<td class="tbl_nobr_one">创建人</td>' +
                    		'</tr>' +
                    		'</table>',
                    margin: '',
                    padding: 5,
                    title: '附件'
                },
                {
                    xtype: 'fieldset',
                    html: '<table id="table_wthtnote" style=\'text-align:center;\' align=\'center\' width=\'100%\' border=\'1\' cellpadding=\'0\' cellspacing="0">' +
                    		'<tr>' +
                    		'<td class="tbl_nobr_one">环节</td>' +
                    		'<td class="tbl_nobr_one">参与人</td>' +
                    		'<td class="tbl_nobr_one">审批操作</td>' +
                    		'<td class="tbl_nobr_one">审批日期</td>' +
                    		'<td class="tbl_nobr_one">审批意见</td>' +
                    		'</tr>' +
                    		'</table>',
                    margin: '',
                    padding: 5,
                    title: '本次审批历史'
                },
                {
                    xtype: 'container',
                    id: 'ctn_userOption',
                    height: '100%',
                    margin: 10,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'spacer'
                        },{
                        	xtype:'hiddenfield',
            				id:'hf_quote',
            				value:''
                        },{
                        	xtype:'hiddenfield',
            				id:'hf_serviceFee',
            				value:''
                        },{
                        	xtype:'hiddenfield',
            				id:'hf_payRatio',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_Se',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_docUid',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_appId',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_taskId',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_nextOwners',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_nextNodes',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_nextOwnerNames',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_stepId',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_SpzNew',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_FgsSpMax',
            				value:'110'
            			},{
                        	xtype:'hiddenfield',
            				id:'h_BzSpMax',
            				value:'112'
            			},{
                        	xtype:'hiddenfield',
            				id:'h_ZjlSpMax',
            				value:'125'
            			},{
                        	xtype:'hiddenfield',
            				id:'h_FzcSpMax',
            				value:'130'
            			},{
                        	xtype:'hiddenfield',
            				id:'h_ZcSpMax',
            				value:'130'
            			},{
                        	xtype:'hiddenfield',
            				id:'h_JumpBpdID',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_JumpFlag',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_JumpLevel',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_JumpStepID',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_LsApproveLevelPfz',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_Pfz',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_SbKcFwfMan',
            				value:''
            			},{
                        	xtype:'hiddenfield',
            				id:'h_WthtID',
            				value:''
                        },{
                            xtype: 'button',
                            style: 'float: left',
                            id:'btn_INSapprove_agree',
                            ui: 'confirm',
                            width: '30%',
                            height: '60px',
                            text: '同意'
                        },
                        {
                            xtype: 'spacer'
                        },
                        {
                            xtype: 'button',
                            style: 'float: left',
                            id:'btn_INSapprove_reservations',
                            width: '30%',
                            height: '60px',
                            ui: 'blue',
                            text: '保留意见'
                        },
                        {
                            xtype: 'spacer'
                        },
                        {
                            xtype: 'button',
                            style: 'float: left',
                            id:'btn_INSapprove_reject',
                            ui: 'decline',
                            width: '30%',
                            height: '60px',
                            text: '拒绝'
                        },
                        {
                            xtype: 'spacer'
                        }
                    ]
                }
         
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'ghmx',
                    title: '工号明细',
                    items: [                        	
                            {
                                xtype: 'list',
                                id:'list_ghmx',
                                disableSelection:true,
                                store: 'ghmxListStore',
                                height: '100%',
                                itemTpl: [
                                	'<tpl if="GhNo%2==1">',
									'<table style=\'background-color: aliceblue;\' align=\'center\' width=\'100%\' border=\'0\' cellpadding=\'0\' cellspacing=\'0\'>',
									'<tpl else>',
									'<table align=\'center\' width=\'100%\' border=\'0\' cellpadding=\'0\' cellspacing=\'0\'>',
									'</tpl>',
                                    '<tr height=\'30\'>',
                                    '<td style=\'border-top:1.0pt solid black;border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px;font-size: 21px;font-weight:bolder;\'>工号:</td>',
                                    '<td style=\'border-top:1.0pt solid black;border-bottom:1.0pt solid black;font-size: 21px;font-weight:bolder;\'>{Gh}</td>',
                                    '<td style=\'border-top:1.0pt solid black;border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>安装地址:</td>',
                                    '<td colspan=3 style=\'border-top:1.0pt solid black;border-right:1.0pt solid black;border-bottom:1.0pt solid black\'>{AzAddress}</td>',
                                    '</tr>',
                                    '<tr height=\'30\'>',
                                    '<td width=\'20%\' style=\'border-left:1.0pt solid black;padding-left:5px\'>型号:</td>',
                                    '<td width=\'13%\'>{Xh}</td>',
                                    '<td width=\'20%\' style=\'border-left:1.0pt solid black;padding-left:5px\'>提升高度:</td>',
                                    '<td width=\'13%\'>{TsHight}</td>',
                                    '<td width=\'20%\' style=\'border-left:1.0pt solid black;padding-left:5px\'>税额:</td>',
                                    '<td width=\'13%\' style=\'border-right:1.0pt solid black\'>{GhSe}</td>',
                                    '</tr>',
                                    '<tr height=\'30\'>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>层/站/门:</td>',
                                    '<td>{Czm}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>载重:</td>',
                                    '<td>{Zz}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>税率（%）:</td>',
                                    '<td style=\'border-right:1.0pt solid black\'>{GhSl}</td>',
                                    '</tr>',
                                    '<tr height=\'30\'>',
                                    '<td style=\'border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>井道高度:</td>',
                                    '<td style=\'border-bottom:1.0pt solid black\'>{ZdHight}</td>',
                                    '<td style=\'border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>安装工法:</td>',
                                    '<td style=\'border-bottom:1.0pt solid black\'>{AzGf}</td>',
                                    '<td style=\'border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>结算金额含税:</td>',
                                    '<td style=\'border-right:1.0pt solid black;border-bottom:1.0pt solid black\'>{JsAmtHs}</td>',
                                    '</tr>',
                                    '<tr height=\'30\'>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>安装款不含税(元):</td>',
                                    '<td>{AzkBhs}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>吊装款不含税(元):</td>',
                                    '<td>{DzkBhs}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>搭棚款不含税(元):</td>',
                                    '<td style=\'border-right:1.0pt solid black\'>{DpkBhs}</td>',
                                    '</tr>',
                                    '<tr height=\'30\'>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>标准金额(元):</td>',
                                    '<td>{AzBzAmt}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>标准金额(元):</td>',
                                    '<td>{DzBzAmt}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>标准金额(元):</td>',
                                    '<td style=\'border-right:1.0pt solid black\'>{DpBzAmt}</td>',
                                    '</tr>',
                                    '<tr height=\'30\'>',
                                    '<td style=\'border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>比率（%）:</td>',
                                    '<td style=\'border-bottom:1.0pt solid black\'>{AzPercent}</td>',
                                    '<td style=\'border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>比率（%）:</td>',
                                    '<td style=\'border-bottom:1.0pt solid black\'>{DzPercent}</td>',
                                    '<td style=\'border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>比率（%）:</td>',
                                    '<td style=\'border-right:1.0pt solid black;border-bottom:1.0pt solid black\'>{DpPercent}</td>',
                                    '</tr>',
                                    '<tr height=\'30\'>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>工艺补贴款不含税(元):</td>',
                                    '<td>{GybtkBhs}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>其他款项不含税(元):</td>',
                                    '<td>{QtkxBhs}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>结算总金额不含税(元):</td>',
                                    '<td style=\'border-right:1.0pt solid black\'>{JsAmtBhs}</td>',
                                    '</tr>',
                                    '<tr height=\'30\'>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>标准金额(元):</td>',
                                    '<td>{GyBzAmt}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>标准金额(元):</td>',
                                    '<td>{QtBzAmt}</td>',
                                    '<td style=\'border-left:1.0pt solid black;padding-left:5px\'>结算总标准金额(元):</td>',
                                    '<td style=\'border-right:1.0pt solid black\'>{JsBzAmt}</td>',
                                    '</tr>',
                                    '<tr height=\'30\'>',
                                    '<td style=\'border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>比率（%）:</td>',
                                    '<td style=\'border-bottom:1.0pt solid black\'>{GyPercent}</td>',
                                    '<td style=\'border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>比率（%）:</td>',
                                    '<td style=\'border-bottom:1.0pt solid black\'>{QtPercent}</td>',
                                    '<td style=\'border-left:1.0pt solid black;border-bottom:1.0pt solid black;padding-left:5px\'>比率（%）:</td>',
                                    '<td style=\'border-right:1.0pt solid black;border-bottom:1.0pt solid black\'>{JsPercent}</td>',
                                    '</tr>',         
                                    '</table>'
                                ],
                            }
                    ]
                },
                {
                xtype: 'container',
                id: 'qtkxmx',
                title: '其他款项明细',
                layout:'vbox',
                items: [
                    {
                    	xtype: 'formpanel',
                        height: 58,
                        scrollable: false,
                        items: [
                            {
                            	xtype: 'fieldset',
                        		layout:'hbox',
		                        items: [
		                            {
		                                xtype: 'textfield',
		                                id: 'QtkxBhs',
		                                style: 'float: left',
		                                inputCls:'align-right ',
		                                width: '33%',
		                                labelWidth:180,
		                                label: '其他款项不含税(元):',
		                                readOnly: true,
		                            },
		                            {
		                                xtype: 'textfield',
		                                id: 'QtBzAmt',
		                                style: 'float: left',
		                                width: '33%',
		                                labelWidth:180,
		                                label: '标准金额(元):',
		                                readOnly: true
		                            },
		                            {
		                                xtype: 'textfield',
		                                id: 'JsPercent',
		                                style: 'float: left',
		                                width: '33%',
		                                labelWidth:180,
		                                label: '比率（%）:',
		                                readOnly: true
		                            },
								]
                            }
                        ]
					}, 
	            	  {
	                    xtype: 'list',
	                    id:'list_qtkx',
	                    store: 'qtkxListStore',  
	                    flex:1,
	                    itemTpl: [
	                        '<table align=\'center\' width=\'100%\' border=\'0\' cellpadding=\'0\' cellspacing="0" class="form-lists-font-size">',
	                        '<tr height=\'22\'>',
	                        '<td colspan=\'6\' class="tbl_nobr_value_one" >{KxMx}</td>',
	                        '</tr>',
	                        '<tr height=\'22\'>',
	                        '<td width=\'13%\'>委托金额:</td>',
	                        '<td width=\'20%\'>{WtAmt}</td>',
	                        '<td width=\'13%\'>标准金额:</td>',
	                        '<td width=\'20%\'>{BzAmt}</td>',
	                        '<td width=\'13%\'>比率（%）:</td>',
	                        '<td width=\'20%\'>{QtPercent}</td>',
	                        '</tr>',
	                        '<tr height=\'22\'>',
	                        '<td width=\'13%\'>备注:</td>',
	                        '<td colSpan=\'5\'>{QtRemarks}</td>',
	                        '</tr>',
	                        '</table>'
	                      ],
	                   },
     
                ]
            },
                
                    {
                        xtype: 'container',
                        scrollable :'vertical',
                        id: 'sp_history',
                        title: '审批历史',
                        html: '<div id="div_scroll_history" class="div_scroll">' +
                        		'<table id="tbl_History" style=\'text-align:center;\' width=\'100%\' align=\'center\' border=\'1\' cellpadding=\'0\' cellspacing="0">' +
                        		'<tr height=\'30\'>' +
                        		'<td class="tbl_nobr">提交次第</td>' +
                        		'<td class="tbl_nobr">参与人</td>' +
                        		'<td class="tbl_nobr">审批操作</td>' +
                        		'<td class="tbl_nobr">审批日期</td>' +
                        		'<td class="tbl_nobr">审批意见</td>' +
                        		'</tr>' +
                        		'</table>' +
                        		'</div>',
                        padding: 5
                    }
                ]
            }
        ]
    }

});

