Ext.define('HelcBPM.store.Remould.R_AssetDetail_WLBJListStore',{
	extend:'Ext.data.Store',
	config:{
		fields:[
			'WlCode',
			'WlName',
			'XhGg',
			'Unit',
			'WlCbjBhs',
			'WlJsj',
			'Num',
			'WlCbHj',
			'WljsjHjHs',
			'Remark'
		],
	},
});