Ext.define('HelcBPM.store.Remould.R_AssetDetail_QTWLBJListStore',{
	extend:'Ext.data.Store',
	config:{
		fields:[
			'QtWlCode',
			'QtWlName',
			'QtXhGg',
			'QtUnit',
			'QtWlCbjBhs',
			'QtWlJsj',
			'QtNum',
			'QtWlCbHj',
			'QtWljsjHjHs',
			'QtRemark'
		],
	},
});