/*
 * File: app/view/MyPanel10.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcOA.view.ReportPassword', {
    extend: 'Ext.Panel',
     ID:'ReportPassword_ID',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '修改密码',
                items: [
                    {
                        xtype: 'button',
                        iconCls: 'home',
                        text: '',
                        listeners:{
                        	tap:function(){
                        		var obj1=Ext.getCmp('Menus_id');
                        		if(!obj1){
                        			obj1=Ext.create('HelcOA.view.Menus');
                        		}
                        		Ext.Viewport.setActiveItem(obj1);
                        	}
                        }

                    }
                ]
            },
            {
                xtype: 'formpanel',
                flex: 1,
                items: [
                    {
                        xtype: 'fieldset',
                        title: '',
                        items: [
                            {
                                xtype: 'passwordfield',
                                inputCls: 'm_Inpur_box',
                                label:'原密码:',
                                labelWidth: '40%',
                                placeHolder: '请输入原密码',
                                id:'oldPassword_id',
                            },
                            {
                                xtype: 'passwordfield',
                                inputCls: 'm_Inpur_box',
                                labelWidth: '40%',
                                label:'新密码:',
                                placeHolder: '请输入新密码',
                                id:'newPassword_id',
                            },
                            {
                                xtype: 'passwordfield',
                                inputCls: 'm_Inpur_box',
                                labelWidth: '40%',
                                label:'确认密码:',
                                placeHolder: '确认新密码',
                                id:'surePassword_id',
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        margin: '15 10 0 10',
                        id:'ofSure_id',
                        text: '确认'
                    }
                ]
            }
        ]
    }

});