/*
 * File: app/view/MyPanel38.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPDA.view.install.faultInformation', {
    extend: 'Ext.Panel',
    id:'FaultInformation_id',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '故障详细信息',
                items: [
                    {
                        xtype: 'button',
                        ui:'back',
                        text: '返回',
                        id:'FaultInformation_id_FH_BUTTON',
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                height: '100%',
                items: [
                    {
                        xtype: 'fieldset',
                        title: '',
                        items: [
                            {
                                xtype: 'textfield',
                                label: '故障名称',
                                id:'duZhuangmins_id',
                                labelWidth: '40%',
                                value: [
                                   
                                ],
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                label: '故障级别',
                                labelWidth: '40%',
                                value: [
                                    
                                ],
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                label: '故障描述',
                                labelWidth: '40%',
                                value: [
                                    
                                ],
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                label: '故障检修图',
                                labelWidth: '40%',
                                value: [
                                  
                                ],
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                label: '检查项目',
                                labelWidth: '40%',
                                value: [
                                    
                                ],
                                readOnly: true
                            }
                        ]
                    }
                ]
            }
        ]
    }

});