/*
 * File: app/store/Public_Screens.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcRemote.store.Public_Screens', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    config: {
        storeId: 'Public_Screens',
        proxy: {
            type: 'jsonp',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreBeforeLoad',
                event: 'beforeload'
            },
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ],
        fields: [
            {
                name: 'id'
            },
            {
                name: 'value'
            },
            {
                name: 'mode'
            },
            {
                name: 'text'
            }
        ]
    },

    onJsonpstoreBeforeLoad: function(store, operation, eOpts) {
        var url = 'http://' + remote.getCmsIP() + '/YL_SCDG/hitachi/screen/getScreenList.do';
        url = url + '?type=' + this.parm;
        store.getProxy().setUrl(url);
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        // console.log(records);
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;

        // 设置-屏幕
        var me = this;

        if(global.isWorklight()) {
            me.parm = parm;
            me.load();
        } else {
            this.setData([
                { value: '10.98.48.135:8000',  password: '111111', mode:'0', text: '科学城展厅(大)' },
                { value: '10.98.48.153:8000',  password: '222222', mode:'1', text: '天津工厂(中)' },

                { value: '10.96.193.35:8000',  password: '0',      mode:'0', text: '测试(大)PDAKAIFA-05' },
                { value: '10.96.193.35:8001',  password: '0',      mode:'1', text: '测试(中)PDAKAIFA-05' },

                { value: '127.0.0.1:8000',     password: '0',      mode:'0', text: '测试(大)127.0.0.1' },
                { value: '127.0.0.1:8001',     password: '0',      mode:'1', text: '测试(中)127.0.0.1' },

                { value: '192.168.4.166:8000', password: '0',      mode:'0', text: '测试(大)192.168.4.166' },
                { value: '192.168.4.166:8001', password: '0',      mode:'1', text: '测试(中)192.168.4.166' },
            ]);
            onSuccess();
        }
    }

});