/*
 * File: app/view/Parts/Warehouse.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcRemote.view.Parts.Warehouse', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Panel',
        'Ext.Label',
        'Ext.Button',
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
        id: 'Parts_Warehouse',
        layout: 'vbox',
        items: [
            {
                xtype: 'panel',
                cls: 'remote-breadCrumb',
                docked: 'top',
                items: [
                    {
                        xtype: 'label',
                        cls: 'remote-breadCrumb-con',
                        html: '配件 > 华东地区',
                        id: 'Parts_Warehouse_title'
                    },
                    {
                        xtype: 'panel',
                        cls: 'remote-breadCrumb-buttonBox',
                        docked: 'right',
                        items: [
                            {
                                xtype: 'button',
                                cls: 'remote-buttonColor-orange',
                                id: 'Parts_Warehouse_BtnReturn',
                                text: '返回'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                cls: [
                    'remote-content',
                    'remote-service'
                ],
                layout: 'vbox',
                items: [
                    {
                        xtype: 'panel',
                        flex: 1,
                        cls: 'remote-service-Parts',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'remote-title',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: 'remote-titleText',
                                        docked: 'left',
                                        html: '省级仓库'
                                    }
                                ]
                            },
                            {
                                xtype: 'dataview',
                                flex: 1,
                                cls: 'remote-Parts-SearchData',
                                id: 'Parts_Warehouse_List',
                                allowDeselect: true,
                                itemTpl: [
                                    '<div class=\'remote-Parts-SearchData-button\'>{subRepoName}</div>'
                                ],
                                store: 'Service_Parts_Warehouse'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 1,
                        cls: 'remote-service-Parts',
                        style: 'border-top:1px solid #07488a',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'remote-title',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: 'remote-titleText',
                                        docked: 'left',
                                        html: '配送城市'
                                    }
                                ]
                            },
                            {
                                xtype: 'dataview',
                                flex: 1,
                                cls: 'remote-Parts-SearchData',
                                id: 'Parts_City_List',
                                itemTpl: [
                                    '<div class=\'remote-Parts-SearchData-button\'>{subRepoName}</div>'
                                ],
                                store: 'Service_Parts_City'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});