/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcApprove.view.ChaoDianZengFei.CDZF_List', {
    extend: 'Ext.tab.Panel',
    id:'CDZF_List',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Spacer'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '增费及超点审批',
                items: [
                    {
                        xtype: 'button',
                        id:'btn_cdzflist_back',
                        ui: 'back',
                        text: '返回'
                    }
                ]
            },
            {
                xtype: 'container',
                title: '待审批',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        height: 60,
                        items: [
                                {
                                    xtype: 'searchfield',
                                    id: 'CDZF_ZL_approved',
                                    width: '90%',
                                    label: '',
                                    placeHolder: '请输入过滤条件',
                                    value: ''
                                },
                            ]
                    },
                    {
                        xtype: 'list',
                        id:'list_cdzf_approval',
                        height: '100%',
                        itemTpl: [
                        	'<tpl if="isOverDate == 1">',
                            '<table align=\'center\' width=\'100%\' border=\'0\' cellpadding=\'0\' cellspacing="0" class="lists-font-size lists-backgroundcolor">',
                            '<tpl else>',
                            '<table align=\'center\' width=\'100%\' border=\'0\' cellpadding=\'0\' cellspacing="0" class="lists-font-size">',
                            '</tpl>',
                            '<tr height=\'22\'>',
                            '<td width=\'12%\'>商机名称:</td>',
                            '<td width=\'50%\'>{oPPORTUNITY}</td>',
                            '<td width=\'15%\'>合同号:</td>',
                            '<td width=\'23%\'>{cONTRACT_ID}</td>',
                            '</tr>',
                            '<tr height=\'22\'>',
                            '<td>买方单位:</td>',
                            '<td>{oPPORTUNITY_ACCOUNT}</td>',
                            '<td>总部营业员:</td>',
                            '<td>{tECH_APPROVER_NAME}</td>',
                            '</tr>',
                            '<tr height=\'22\'>',
                            '<td>使用单位:</td>',
                            '<td>{qUOTE_FINAL_USER}</td>',
                            '<td>跟单组织:</td>',
                            '<td>{oRGANIZATION_OPPTY}</td>',
                            '</tr>',
                            '<tr height=\'22\'>',
                            '<td>大客户:</td>',
                            '<td>{aTTR_05}{aTTR_07}</td>',
                            '<td>重点项目部合同(不含进口梯种):</td>',
                            '<td>{aTTR_06}</td>',
                            '</tr>',
                            '</table>'
                        ],
                        onItemDisclosure: true,
                        store:'AddServiceApprovedStore'
                    },
                ]
            },
            {
                xtype: 'container',
                title: '已审批',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        height: 60,
                        items: [
                                {
                                    xtype: 'searchfield',
                                    id: 'CDZF_TBJXX_approved',
                                    width: '90%',
                                    label: '',
                                    placeHolder: '请输入过滤条件',
                                    value: ''
                                },
                                {
                                	xtype: 'button',
                                	width: '10%',
                                	id: 'btn_CDZF_TBJXX_approvedSearch',
                                	text: '搜索'
                                }
                            ]
                    },
                    {
                        xtype: 'list',
                        id:'list_cdzf_approved',
                        store: 'CDZFApprovedStore',
                        height: '100%',
                        itemTpl: [
                            '<table align=\'center\' width=\'100%\' border=\'0\' cellpadding=\'0\' cellspacing="0" class="lists-font-size">',
                            '<tr height=\'22\'>',
                            '<td width=\'12%\'>商机名称:</td>',
                            '<td width=\'50%\'>{oPPORTUNITY}</td>',
                            '<td width=\'15%\'>合同号:</td>',
                            '<td width=\'23%\'>{cONTRACT_ID}</td>',
                            '</tr>',
                            '<tr height=\'22\'>',
                            '<td>买方单位:</td>',
                            '<td>{oPPORTUNITY_ACCOUNT}</td>',
                            '<td>总部营业员:</td>',
                            '<td>{tECH_APPROVER_NAME}</td>',
                            '</tr>',
                            '<tr height=\'22\'>',
                            '<td>使用单位:</td>',
                            '<td>{qUOTE_FINAL_USER}</td>',
                            '<td>跟单组织:</td>',
                            '<td>{oRGANIZATION_OPPTY}</td>',
                            '</tr>',
//                            '<tr height=\'22\'>',
//                            '<td>审批日期:</td>',
//                            '<td>{shenpiriqi}</td>',
//                            '<td>版本号:</td>',
//                            '<td>{banbenhao}</td>',
//                            '</tr>',
                            '</table>'
                        ],
                        onItemDisclosure: true
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                id:'btn_cdzf_prepage_approved',
                                flex: 1,
                                iconCls: 'arrow_left',
                                text: '上一页'
                            },
                            {
                                xtype: 'spacer',
                                flex: 1
                            },
                            {
                                xtype: 'container',
                                id: 'ctn_showCurrPage',
                                html: '当前页数：1'
                            },
                            {
                                xtype: 'spacer',
                                flex: 1
                            },
                            {
                                xtype: 'button',
                                id:'btn_cdzf_nextpage_approved',
                                flex: 1,
                                ui: 'forward',
                                iconAlign: 'right',
                                iconCls: 'arrow_right',
                                text: '下一页'
                            },
                            {
                            	xtype:'hiddenfield',
                				id:'cdzf_currPage',
                				value:'0'
                            },{
                            	xtype:'hiddenfield',
                				id:'cdzf_isLastPage',
                				value:'N'
                            },{
                            	xtype:'hiddenfield',
                				id:'cdzf_maxPage',
                				value:'1'
                            },{
                            	xtype:'hiddenfield',
                				id:'cdzf_listTabFlag',
                				value:'1'
                            },
//                            {
//                            	xtype: 'hiddenfield',
//                            	id: 'CDZF_pageIndex',
//                            },
//                            {
//                            	xtype: 'hiddenfield',
//                            	id: 'CDZF_LastPage',
//                            }
                        ]
                    }
                ]
            }
        ]
    }

});