Ext.define('HelcPDA.model.maintain.MaintenaceProtectPrjectModel',{
	extend:'Ext.data.Model',
	config:{
		fields : [
		          'TASK_NAME',
		          'PLAN_STATUS',
		          'TASK_DESCRIPTION',
		          'TASK_ROW_ID',
		          'PLAN_TIMES',
		          'IS_MUG3',
		          'XCNAME_DISPLAY',
		          'TASKNAME_DISPLAY',
		          'TASK_TYPE',
		          'ID',
		          'I_Index',
		          'TemplateTaskSubId',
		          ]
	}
});