/*
 * File: app/view/bbPanel4.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPDA.view.report.installcomplete.InstallComplete_Detail_View', {
    extend: 'Ext.Panel',
    id:'installComplete_Detail_View',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '安装完工报表',
                items: [
                    {
                        xtype: 'button',
                        ui: 'back',
                        text: '返回',
                        id:'instalComplet_back'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'textfield',
                        label: '时间',
                        id:'Install_date',
                        placeHolder:'选择时间',
                        readOnly:true,
                        listeners:{
                        	focus:function(){
                        		iniMydate1('Install_date','报表时间');
                        	}
                        }
                    }
                ]
            },
            {
            	xtype:'container',
            	docked: 'top',
            	height:'100%',
            	items:[
            	       {
            	    	   xtype:'fieldset',
            	    	   title:'<div style="text-align:center;color:#000;" id="detail_title">全国<div>',
            	    	   height:'100%',
            	    	   docked:'top',
            	    	   layout:{
            	    		 type:'vbox'  
            	    	   },
            	    	   items:[
            	    	         {
            	    	               xtype: 'list',
            	    	               //docked: 'bottom',
            	    	               height: '75%',
            	    	               data: [
            	    	            ],
            	    	             itemId: 'mylist7',
            	    	             store:'InstallCompleteStore1',
            	    	             itemTpl: [
            	    	              '<table border=0 width=100% style="color:#666">',
            	    	              '    <tr>',
            	    	              '    <td colspan="3" width=60% style="color:#000;">{YEAR}{MONTH}</td>',
            	    	              '  </tr>',
            	    	              '  <tr>',
            	                      '    <td width=32%>指标:{COMPLETE_TARGET}</td>',
            	                      '    <td width=32% style="padding-right:5px;">完工量:{COMPLETE_COUNT}</td>',
            	                      '    <td width=32%>完工率:{COMPLETE_RATE}</td>',
            	                      '  </tr>',
            	    	              '</table>'
            	    	                    ],
            	    	},
            	    	  {
                            xtype:'textfield',
                             id:'install_QGZB',
                             //docked: 'bottom',
                             value:'',
                             hidden:true,
                             readOnly:true,
                          }
            	    	
            	    	         ]
            	       }
                 
            	       ]
            }
            
        ]
    }

});

function iniMydate1(need_text_id,title){
	var Panel=Ext.getCmp('myPicker');
	if(Panel){
		Panel.destroy();
	}
	if(!Mydate_show){
		var Mydate_show=Ext.Viewport.add({
	         xtype: 'picker',
	         ui: 'dark',
	         id:'myPicker',
	         doneButton: '确定',
	         cancelButton: '取消',
	         modal:true,
	         toolbar: {
	             ui: 'light',
	             title: title,
	         },
	         slots: [
	             {
	                 xtype: 'pickerslot',
	                 name: 'year',
	                 title: 'MyPickerSlot0',
	                 id:'slots001',
	                 data: [
	                     {
	                         text: ''+new Date().getFullYear()-1+'年',
	                         value: ''+new Date().getFullYear()-1
	                     },
	                     {
	                         text: ''+new Date().getFullYear()+'年',
	                         value: ''+new Date().getFullYear()
	                     }
	                 ]
	             },
	             {
	                 xtype: 'pickerslot',
	                 name: 'month',
	                 title: 'MyPickerSlot00',
	                 id:'slots011',
	                 data: [
	                     {
	                         text: '全部',
	                         value: '全部'
	                     },
	                     {
	                         text: '1月',
	                         value: '1'
	                     },
	                     {
	                         text: '2月',
	                         value: '2'
	                     },
	                     {
	                         text: '3月',
	                         value: '3'
	                     },
	                     {
	                         text: '4月',
	                         value: '4'
	                     },
	                     {
	                         text: '5月',
	                         value: '5'
	                     },
	                     {
	                         text: '6月',
	                         value: '6'
	                     },
	                     {
	                         text: '7月',
	                         value: '7'
	                     },
	                     {
	                         text: '8月',
	                         value: '8'
	                     },
	                     {
	                         text: '9月',
	                         value: '9'
	                     },
	                     {
	                         text: '10月',
	                         value: '10'
	                     },
	                     {
	                         text: '11月',
	                         value: '11'
	                     },
	                     {
	                         text: '12月',
	                         value: '12'
	                     }
	                 ]
	             }
	             ],
	             listeners:{
	            	 change:function(obj, value, eOpts ){
	            	 Ext.getCmp(need_text_id).setValue(value.year+"-"+value.month);
	            	 },
	             }
		 });
		Mydate_show.show();
	}
	
}
