/*
 * File: app/view/InstallatoinTasksFactoryPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPDA.view.install.installtoreportcheck.InstallationTasksReportCheckPanel', {
    extend: 'Ext.Panel',
    id:'installationTasksReportCheckPanel',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.tab.Panel'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '报检任务',
                items: [
                    {
                        xtype: 'button',
                        id:'BJ_Back',
                        ui: 'back',
                        text: '返回'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                        },
                        iconCls: 'refresh',
                        id:'updateReportCheck',
                        text: '更新'
                    }
                 
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'label',
                        html: '',
                        id:'NUM1',
                        margin: '0 0 0 20'
                    },
                    {
                        xtype: 'spacer'
                    },{
                        xtype: 'label',
                        html: '',
                        id:'NUM2',
                        margin: '0 0 0 20'
                    },
                    {
                        xtype: 'spacer'
                    },{
                        xtype: 'label',
                        html: '',
                        id:'NUM3',
                        margin: '0 0 0 20'
                    }
                ]
            },
            {
                xtype: 'list',
                data: [
                ],
                height: '100%',
                itemId: 'mylist7',
                id:'check_list',
                store:'InstallatoinTasksReportCheckStore',
                itemTpl: [
                    '<table border=0 width=100%>',
                    '    <tr height=20>',
                    '        <td width=70%>',
                    '            <span style="font-size:18px;color:#000;">{ENGCONTRACT_NUMBER}</span>',
                    '        </td>',
                    '    </tr>',
                    '    <tr height=18>',
                    '        <td><span style="">{CUSTOMER_NAME}</span></td>',
                    '    </tr>',
                    '    <tr height=18>',
                    '        <td><span style="">未提交:{NUM4}</span>&nbsp;&nbsp;&nbsp;&nbsp;<span style="">已提交:{NUM5}</span></td>',
                    '    </tr>',
                    '</table>'
                ],
                onItemDisclosure: true
            },
            {
            	xtype:'hiddenfield',
            	id:'toView',
            	value:''
            }
              ]
                   },
                    

});