Ext.define('HelcBPM.store.Maintain.M_ghbjmxListStore',{
	extend:'Ext.data.Store',
	config:{
		fields:[
			'Gh',
			'GhTzXh',
			'GhDtZt',
			'GhCpLb',
			'GhSplZh',
			'GhWlQwjHj',
			'GhWlSjHj',
			'GhWlQwjHjHs',
			'GhWlQwjFl',
			'GhZxRgf',
			'LineId'
		],
	},
});