Ext.define('HelcBPM.store.Maintain.M_MaterialDetailListStore',{
	extend:'Ext.data.Store',
	config:{
		fields:[
			'WlCode',
			'DkhXyjHs',
			'DkhZkl',
			'DgWlQwj',
			'WlName',
			'GcBzCb',
			'DgwlQwjHs',
			'Num',
			'YjFgsCgCb',
			'WlQwjHj',
			'SpJsFs',
			'YjXsLrl',
			'SjHj',
			'Sp1',
			'Spl',
			'WlqwjHjHs',
			'Sp2',
			'SplZh',
			'WlhFl'
		],
	},
});