/*
 * File: app/view/MyContainer24.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcApprove.view.Seting.UserHistory', {
    extend: 'Ext.Container',
    id:'UserHistory',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Label'
    ],

    config: {
    	scrollable: 'vertical',
        html: '<table id="userHistoryTable" width="100%" border="1" cellspacing="0" cellpadding="0"><tr>      <td height="30"><div align="center">注册日期</div></td>         <td height="30"><div align="center">用户名</div></td>         <td height="30"><div align="center">设备标识</div></td>         <td height="30"><div align="center">是否本机</div></td>         <td height="30"><div align="center">备注信息</div></td>         <td height="30"><div align="center">最后使用时间</div></td>         <td height="30"><div align="center">状态</div></td>         <td height="30"><div align="center">操作</div></td>       </tr>   </table>',
        padding: 10,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '设备用户查看（仅显示最近100条记录）',
                items: [
                    {
                        xtype: 'button',
                        id:'btn_userhistory_back',
                        ui: 'back',
                        text: '返回'
                    }
                ]
            },
            {
                xtype: 'label',
//                html: '<font id="userHistoryFont" color="#FF0000">1、您当前的设备标识后8位为...94fcd18b!<br /> 2、以下显示记录为该用户或者该设备曾经的使用情况，解除指定锁定后将无法再次使用指定用户在指定设备上登录。若需要再次启用，请联系管理员。</font><font color="#FF0000"><br /> 3、若您想知道所有的推送历史，请联系系统管理员导出！</font>',
                html: '<font id="userHistoryFont" color="#FF0000"></font>',
                margin: '0 0 5 0'
            }
        ]
    }

});