/*
 * File: app/view/bbPanel5.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPDA.view.report.maintainbb.KeepAchievement_Detail_View', {
    extend: 'Ext.Panel',
    id:'keepAchievement_Detail_View',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '全国合计',
                items: [
                    {
                        xtype: 'button',
                        ui: 'back',
                        text: '返回',
                        id:'keepAchiv_back'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                flex: 1,
                items: [
                    {
                        xtype: 'container',
                        title: '保修',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '当月在保台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_WAR_AMOUNT',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '当月预算台量',
                                                id:'REPAIR_BUDGET',
                                                labelWidth: '50%',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '当月完成率',
                                                id:'REPAIR_BUDGET_RATE',
                                                labelWidth: '50%',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '全年预算台量',
                                                labelWidth: '50%',
                                                id:'REPAIR_BUDGET_QN',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '全年完成率',
                                                labelWidth: '50%',
                                                id:'REPAIR_BUDGET_RATE_QN',
                                                value: [
                                                  
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '上月在保台量',
                                                labelWidth: '50%',
                                                id:'LST_MON_WAR_AMOUNT',
                                                value: [
                                                  
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '开始台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_WAR_STAT_AMOUNT',
                                                value: [
                                                 
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '到期台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_WAR_END_AMOUNT',
                                                value: [
                                                  
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '自保台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_WAR_OWN_AMOUNT',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '外协台量',
                                                id:'CUR_MON_WAR_ASS_AMOUNT',
                                                labelWidth: '50%',
                                                value: [
                                                
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '他保台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_WAR_OTH_AMOUNT',
                                                value: [
                                                  
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '直梯台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_WAR_LIFT_AMOUNT',
                                                value: [
                                                
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '扶梯台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_WAR_ESCA_AMOUNT',
                                                value: [
                                               
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '保养',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '当月在保台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_AMOUNT',
                                                value: [
                                                
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '当月预算台量',
                                                labelWidth: '50%',
                                                id:'MAINTAINA_BUDGET',
                                                value: [
                                                  
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '当月完成率',
                                                labelWidth: '50%',
                                                id:'MAINTAINA_BUDGET_RATE',
                                                value: [
                                                 
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '全年预算台量',
                                                labelWidth: '50%',
                                                id:'MAINTAINA_BUDGET_QN',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '全年完成率',
                                                labelWidth: '50%',
                                                id:'MAINTAINA_BUDGET_RATE_QN',
                                                value: [
                                            
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '上月在保台量',
                                                labelWidth: '50%',
                                                id:'LST_MON_MAI_AMOUNT',
                                                value: [
                                                  
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '当月',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_AMOUNT1',
                                                value: [
                                              
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '平均单价(元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_PRICE',
                                                value: [
                                                  
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '总金额(k元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_SUM',
                                                value: [
                                                    
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '新签',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_NEW_AMOUNT',
                                                value: [
                                                    
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '平均单价(元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_NEW_PRICE',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '总金额(k元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_NEW_SUM',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '续保',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_REN_AMOUNT',
                                                value: [
                                                    
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '平均单价(元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_REN_PRICE',
                                                value: [
                                                  
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '总金额(k元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_REN_SUM',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '复回',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_RET_AMOUNT',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '平均单价(元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_RET_PRICE',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '总金额(k元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_RET_SUM',
                                                value: [
                                                    
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '退保',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_CAN_AMOUNT',
                                                value: [
                                                  
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '平均单价(元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_CAN_PRICE',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '总金额(k元)',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_CAN_SUM',
                                                value: [
                                                    
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '自保',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '未到期台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_OWN_AMOUNT',
                                                value: [
                                                    
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '已到期台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_OWNED_AMOUNT',
                                                value: [
                                                    
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '委托',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '未到期台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_OTH_AMOUNT',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '已到期台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_OTHED_AMOUNT',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '直梯台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_LIFT_AMOUNT',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '扶梯台量',
                                                labelWidth: '50%',
                                                id:'CUR_MON_MAI_ESCA_AMOUNT',
                                                value: [
                                                   
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});