Ext.define('HelcAgent.model.OpportunityManagement.Project_New.BusinessAgentModel',{
	extend:'Ext.data.Model',
	config:{
		fields:[
		     'Comments',//'',
		     'LineNumber',//'1',
		     'PerformanceShared',//'0',
		     'RegistrationDate',//'',
		     'PerformanceCountCal',//'0',
		     'LeadStatus',//'',
		     'LeadId',//线索状态
		     'ElevatorCount',//'0',
		     'Agent',//'佛山市冠立电梯有限公司',
		     'OpptyId2',//'1-3X4XC8',
		     'Id',//'1-QXSWNT',
		     'PrimaryField',//'Y',
		     'HELId',//'1-39UEIT'
		]
	}
});