/*
 * File: app/view/wzxx2.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPDA.view.map.MapAroundPeopleView', {
    extend: 'Ext.Panel',
    id:'mapAroundPeopleView',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '要查找的人员',
                items: [
                    {
                        xtype: 'button',
                        ui: 'back',
                        text: '返回',
                        id:'mapBack'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        text: '全部',
                        id:'choice_ArroudAll'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        id:'tap_500',
                        text: '500',
                        handler:function(button,e){
                        	Ext.getCmp('tap_500').setCls('');
                        	Ext.getCmp('tap_1000').setCls('l_text_color');
                        	Ext.getCmp('tap_2000').setCls('l_text_color');
                        }
                    },
                    {
                        xtype: 'button',
                        id:'tap_1000',
                        cls: 'l_text_color',
                        text: '1000',
                        handler:function(button,e){
                        	Ext.getCmp('tap_500').setCls('l_text_color');
                        	Ext.getCmp('tap_1000').setCls('');
                        	Ext.getCmp('tap_2000').setCls('l_text_color');
                        }
                    },
                    {
                        xtype: 'button',
                        id:'tap_2000',
                        cls: 'l_text_color',
                        text: '2000',
                        handler:function(button,e){
                        	Ext.getCmp('tap_500').setCls('l_text_color');
                        	Ext.getCmp('tap_1000').setCls('l_text_color');
                        	Ext.getCmp('tap_2000').setCls('');
                        }
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'label',
                        html: '单位：m',
                        margin: '0 20 0 0'
                    }
                ]
            },
            {
                xtype: 'list',
                data: [
                 
                ],
                height: '100%',
                itemId: 'mylist8',
                id:'choice_AroundList',
                store:'MapAroundPeopleStore',
                itemTpl: [
                    '<table border=0 width=96% style="color:#666">',
                    '  <tr>',
                    '      <td style="color:#000;font-size:22px;">{USERNAME}</td>',
                    '      <td style="text-align: right"></td>',
                    '  </tr><br>',
                    '  <tr>',
                    '      <td colspan="2">{CONTENT}</td>',
                    '  </tr>',
                    '</table>'
                ],
                onItemDisclosure: true
            },
            {
            	xtype:'hiddenfield',
            	id:'METER',
            	value:''
            }
              
        ]
    }

});