/*
 * File: app/view/OpportunityOutflowReasonAnalysisList.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPAD.view.OpportunityManagement.Project_New.OpportunityOutflowReasonAnalysisList', {
    extend: 'Ext.Container',
    id:'opportunityoutflowreasonanalysislist_new_id',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.SegmentedButton',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '商机流失原因分析列表',
                cls:'textf',
                items: [
                    {
                    	id:'opportunityoutflowreasonanalysislist_new_id_FH',
                        xtype: 'button',
                        ui: 'back',
                        text: '返回'
                    },{
                    	id:'loseOpportunity',
                    	xtype:'hiddenfield'
                    },
                    {
                        xtype: 'spacer'
                    },{
        				id:'opportunityLose',
        				xtype:'button',
        				text:'提交商机流失',
        				hidden:true
        			},{
                    	id:'managerOPerationLoseReason',
                    	xtype:'button',
                    	text:'商机流失操作',
                    	hidden:true,
                    	handler:function(){
                    		
                    		var menu = Ext.create('Ext.Menu',{
                    			minWidth:'50%',
                    			items:[{
                    				id:'agreeOpportunityLose',
                    				xtype:'button',
                    				text:'同意商机流失',
                    			},{
                    				xtype:'spacer'
                    			},{
                    				id:'refuseOpportunityLose',
                    				xtype:'button',
                    				text:'拒绝商机流失',
                    			},{
                    				xtype:'spacer'
                    			},{
                    				xtype:'button',
                    				text:'返回',
                    				handler:function(b,e){
                    					Ext.Viewport.hideMenu('right');
                    				}
                    			}]
                    		});
                    		Ext.Viewport.setMenu(menu, {
                                side: 'right',
                                reveal: false
                            });
                    		Ext.Viewport.showMenu('right');
                    	}
                    }
                    
                ]
            },
            {
            	id:'buildAndDelete',
                xtype: 'segmentedbutton',
                margin: 10,
                cls:'textf',
                height:'8%',
                items: [
                    {
                    	id:'opportunityoutflowreasonanalysislist_new_id_ZJ',
                        xtype: 'button',
                        text: '增加'
                    },
                    {
                    	id:'opportunityoutflowreasonanalysislist_new_id_SC',
                        xtype: 'button',
                        text: '删除'
                    }
                ]
            },
            {
            	id:'opportunityoutflowreasonanalysislist_new_id_list',
                xtype: 'list',
                height: '100%',
                store:'OpportunityOutflowReasonStore',
                itemTpl: [
					'<table border=0 width=100% style="color:#666" class="textf">'+
					'  <tr>'+
					'     <td width=10% rowspan="3">'+
					'        <div name="groupkung_opportunityoutflowreasonanalysislist" style="{OpptyType};<tpl if="CheckFlag==\'Y\'">color:#e03a3e;</tpl>" class="p_judge_box2" id="conkung_opportunityoutflowreasonanalysislist">3</div>'+
					'     </td>'+
					'     <td width=80%><span style="{OpptyType}">{OpptyType}</span>	{OpptyLoseReasonType }	{OpptyLoseReason }</td>'+
					'     <td width=20%></td>'+
					'  </tr>'+
					'</table>',
                    //'<div><input type=\'checkbox\'>　商机类型	流失原因类型	流失原因	确定</div>'
                ],
                onItemDisclosure: true
            }
        ]
    }

});