/*
 * File: app/view/MaintenancePlanDetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */



Ext.define('HelcPDA.view.maintain.MaintenancePlanDetailPanel', {
    extend: 'Ext.Panel',
    id:'DetailPanel',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Label',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.field.Spinner',
        'Ext.field.TextArea'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
//                        handler: function(button, e) {
//                            Ext.Viewport.setActiveItem(Ext.getCmp('Maintainlist'));
//                        },
                        ui: 'back',
                        text: '返回',
                        id:'buttonMaintain'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'label',
                        html: '保养计划'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                        	if(Ext.getCmp('moreright')){
                            	Ext.getCmp('moreright').destroy();
                            }
                        	
                            var menu = Ext.create('Ext.Menu', {
                            	id: 'moreright',
                                items: [
                                {
                                    text: '保存',
                                    id:'savaMaintenaceDetail',
                                    hidden:false,
                                    handler:function(button,e){
                                    	 Ext.Viewport.hideMenu('right');
                                    }
                                },
                                {
                                    text: '重置',
                                    id:'resetValue',
                                    hidden: true,
                                    handler:function(button,e){
                                   	 Ext.Viewport.hideMenu('right');
                                   }
                                },
                                {   
                                    text: '提交',
                                    id:'submitAll',
                                    hidden:false,
                                    handler:function(button,e){
                                   	 Ext.Viewport.hideMenu('right');
                                   }
                                },
                                {
                                    style: 'border:none;background: transparent;',
                                    disbaled: true
                                },
                                {
                                    text: '指示',
                                    id: 'pointing',
                                    handler:function(button,e){
                                   	 Ext.Viewport.hideMenu('right');
                                   }
                                },
                                {   
                                	xtype:'button',
                                    text: '换件',
                                    id:'changePiece',
                                    hidden: true,
                                    handler:function(button,e){
                                   	 Ext.Viewport.hideMenu('right');
                                   },
                                },
                                {
                                    text: '回收',
                                    id:'toGetBack',
                                    handler:function(button,e){
                                   	 Ext.Viewport.hideMenu('right');
                                   }
                                },
                                {   
                                	xtype:'button',
                                    text: '上传',
                                    id:'uploadPiece',
                                    hidden: true,
                                    handler:function(button,e){
                                   	 Ext.Viewport.hideMenu('right');
                                   },
                                },
                                {
                                    style: 'border:none;background: transparent;',
                                    disbaled: true
                                },
                                {   
                                	xtype:'button',
                                	text: '实时监控',
                                	id:'realtimeJK',
                                	handler:function(button,e){
                                		Ext.Viewport.hideMenu('right');
                                	},
                                },
                                {   
                                	xtype:'button',
                                	text: '激活调试',
                                	id:'activateTest',
                                	handler:function(button,e){
                                		Ext.Viewport.hideMenu('right');
                                	},
                                },
                                {
                                	style: 'border:none;background: transparent;',
                                	disbaled: true
                                },
                                {   
                                	xtype:'button',
                                	text: '作业打卡',
                                	id:'btn_MaintainSencCard',
                                	handler:function(button,e){
                                		Ext.Viewport.hideMenu('right');
                                	},
                                },
                                {   
                                	xtype:'button',
                                	text: '报告书',
                                	id:'btn_report',
                                	handler:function(button,e){
                                		Ext.Viewport.hideMenu('right');
                                	},
                                },
                                
                                
                                ]
                            });
                            
                        	if(!(seeatid==person_id)){
                        		var savaMaintenaceDetail=Ext.getCmp('savaMaintenaceDetail'); 
                        		var submitAll=Ext.getCmp('submitAll'); 
                        		savaMaintenaceDetail.setHidden(true);
                        		submitAll.setHidden(true);
                        	}
                        	
                      	     //假设已经完成了改选项，对按键进行屏蔽
                        	var tid=Ext.getCmp('hidden2MP_ID').getValue();
                        	var query={tid:tid};	
                        	WL.JSONStore.get(collectionName).find(query).then(function(res){
                   	    		var stexts=res[0].json.stext;
                   	    		if(stexts.PlanStatus=="已提交"||stexts.PlanStatus=='正在等待提交'||stexts.PlanStatus=='已完成'){
                   	    			Ext.getCmp('savaMaintenaceDetail').setHidden(true); 
                   	    			Ext.getCmp('submitAll').setHidden(true);
                   	    			Ext.getCmp('resetValue').setHidden(true);
                   	    			Ext.getCmp('changePiece').setHidden(true);
                   	    		}
                   	    	}).fail(function(){
                   	    		WL.Toast.show("修改初始化数据失败");
                   	    	});
                   	    	 
                   	    	Ext.Viewport.setMenu(menu, {
                   	    		side: 'right',
                   	    		reveal: false
                   	    	});
                            
                            Ext.Viewport.showMenu('right');

                            if(Ext.getCmp('ISACTIVE').getValue() != "遥监已激活"){
                    			Ext.getCmp('activateTest').setHidden(true);
                    		}
                        },
                        itemId: 'mybutton5',
//                        iconCls: 'more',
                        text: '更多'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                id:'mTab',
                height: '100%',
                items: [
                    {
                        xtype: 'container',
                        title: '录入数据',
                        id:'mC_1',
                        items: [
                            {
                                xtype: 'formpanel',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        title: '输入时间项：',
                                        items: [
                                                { 
                                                	xtype:'textfield',
                                                	label: '实际开始',
                                                    placeHolder: '选择日期',
                                                    labelWidth: '50%',
                                                    id:'ACTUAL_START_DT',
                                                    readOnly:true,
                                                    listeners:{
                                                    	focus:function(){
                                                    		need_text_id='ACTUAL_START_DT';
                                                			initDate(Ext.getCmp('ACTUAL_START_DT').getValue(),'实际开始');
                                                			picker_show.show();
                                                    	},
                                                    	change:function(){
                                                    		RealTimeCompare(Ext.getCmp('ACTUAL_START_DT').getValue(),Ext.getCmp('ACTUAL_END_DT').getValue());
                                                    	    Ext.getCmp('PLAN_START_DT').setValue(Ext.getCmp('ACTUAL_START_DT').getValue());
                                                    	}
                                                    }
                                                },
                                            {
                                                xtype: 'textfield',
                                                label: '实际结束',
                                                placeHolder: '选择日期',
                                                labelWidth: '50%',
                                                id:'ACTUAL_END_DT',
                                                value: [
                                                ],
                                                readOnly:true,
                                                listeners:{
                                                	focus:function(){
                                                		need_text_id='ACTUAL_END_DT';
                                            			initDate(Ext.getCmp('ACTUAL_END_DT').getValue(),'实际结束');
                                            			picker_show.show();
                                                	},
                                                	change:function(){
                                                		RealTimeCompare(Ext.getCmp('ACTUAL_START_DT').getValue(),Ext.getCmp('ACTUAL_END_DT').getValue());
                                                		Ext.getCmp('PLAN_END_DT').setValue(Ext.getCmp('ACTUAL_END_DT').getValue());
                                                	}
                                                }
                                            },{
                                                xtype: 'textfield',
                                                label: '实际时长',
                                                labelWidth: '50%',
                                                id:'ACTUAL_Using_Date',
                                                value: [
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '其他输入项：',
                                        items: [
                                            {
                                                xtype: 'selectfield',
                                                label: '实际人员1',
                                                labelWidth: '50%',
                                                id:'ACTUAL_EMP_ID1',
                                                placeHolder: '选择人员',
                                                readOnly: false,
                                                autoSelect:true,
                                                options:[],
                                                listeners:{
                                                	change : function(record,element,index,e){
                                  					//  WL.Toast.show(Ext.getCmp("ACTUAL_EMP_ID1").getValue());
                                  				}
                                                }
                                            },
                                            {
                                                xtype: 'selectfield',
                                                label: '实际人员2',
                                                labelWidth: '50%',
                                                id:'ACTUAL_EMP_ID2',
                                                placeHolder: '选择人员',
                                                readOnly: false,
                                                options: [
                                                ]
                                            },
                                            {
                                                xtype: 'selectfield',
                                                label: '实际人员3',
                                                labelWidth: '50%',
                                                id:'ACTUAL_EMP_ID3',
                                                placeHolder: '选择人员',
//                                                hidden:true,
                                                readOnly: false,
                                                options: [
                                                ]
                                            },
//                                            {
//                                                xtype: 'textfield',
//                                                id:'GOV_CHECK_TIME',                                               
//                                                label: '年检时间',
//                                                labelWidth: '50%',
//                                                placeHolder: '选择日期',
//                                                readOnly:true,
//                                                listeners:{
//                                                	focus:function(){
//                                                		initDate1('GOV_CHECK_TIME','年检时间');
//                                                	}
//                                                }
//                                                
//                                            },
                                            {
                                                xtype: 'spinnerfield',
                                                label: '交通时间',
                                                labelWidth: '50%',
                                                id:'TRAFFIC_TIME',
                                                readOnly: false,
                                                minValue: 0,
                                                stepValue: 5
                                            }
                                        ]
                                    },
                                    //MUG4屏蔽 czq
                                    /*
                                    {
                                        xtype: 'fieldset',
                                        title: '附件：',
                                        items: [
                                            {
                                                xtype: 'panel',
                                                style: 'border-bottom:#ccc 1px dotted',
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'start',
                                                    pack: 'center'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        margin: 10,
                                                        width: 120,
                                                        text: '拍照',
                                                        id:'take_picture',
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        margin: 10,
                                                        width: 120,
                                                        text: '浏览',
                                                        id:'see_picture'
                                                    }
                                                ]
                                            },
                                            {
//                                        		xtype: 'dataview',
                                        		xtype:'list',
                                                id: 'picture_listV',
                                                width:"100%",
                                                scrollable: false,
                                                store :'MaintenacePictureStore',
                                                data:[
                                                      ],
                                                itemTpl : [
                                                           '<div style="width:100%; margin:0; padding:0;">',
                                                           '    <img src="{src}" style="float:left; margin:0; padding:0;width:40px;height:30px"></img>',
                                                           '    <div style="float:right;margin:0;">',
                                                           '    <img  id="2" style="width:18px;" src="images/delete01.png"/>',
                                                           '    </div>',
                                                           '</div>'
                                                ],
                                        },
                                            {
                                                xtype: 'autoTextArea',
                                                id:'COMMENTS',
                                                label: '备注',
                                                labelWidth: '20%',
                                                placeHolder: '录入备注'
                                            }
                                        ]
                                    }
                                    */
                                ]
                            }
                        ]
                    },
                    {
                    	xtype: 'container',
                    	title: '目测、检查项目',
                    	layout: 'vbox',
                    	items:[
                    	   {
                    		   xtype:'list',
                    		   flex:1,
                    		   id:'maintenacePej_MuCe',
                    		   store:'MaintenaceProtectPrject_MuCeStore',
                    		   itemTpl:[
                    		       '<div style="backgroud-color:red;">{TASK_NAME}</div><div>{TASK_DESCRIPTION}</div>'
                    		   ],
                    	   }
                    	],
                    },
                    {
                        xtype: 'container',
                        title: '测量记录项目',
                        layout:'vbox',
                        id:'mC_2',
                        items:[
                		       {
                	         xtype:'list',
                	         flex:1,
                	         scrollable:true,
                	         id:'maintenacePej',
                	         store:'MaintenaceProtectPrjectStore',
//                	         onItemDisclosure:true,
                	         itemTpl:[ '<div style="backgroud-color:red;">{TASK_NAME} / {PLAN_STATUS}</div><div>{TASK_DESCRIPTION}</div>'],
                		       },  
                		]
                    },
                     {
                    xtype: 'container',
                    title: '查看数据',
                    id:'mC_3',
                    items: [
                        {
                            xtype: 'formpanel',
                            height: '100%',
                            items: [{
                                	//用于存放 mainItem Task_row_Id
                    				xtype:'hiddenfield',
                    				id:'hidden2Task_row_Id',
                    				value:''
                    			},
                    			{
                                	//用于存放 mainItem MP_ID
                    				xtype:'hiddenfield',
                    				id:'hidden2_stext_MP_ID',
                    				value:''
                    			},{
                                	//用于存放 mainfields tcode
                    				xtype:'hiddenfield',
                    				id:'hidden2_Tcode',
                    				value:''
                    			},
                    			{
                                	//用于存放 mainfields tid
                    				xtype:'hiddenfield',
                    				id:'hidden2_Tid',
                    				value:''
                    			},{
                                	//用于存放 mainitem tid
                    				xtype:'hiddenfield',
                    				id:'hidden2_maintem_Tid',
                    				value:''
                    			},{
                    				//用于存放maifield MP_ID
                    				xtype:'hiddenfield',
                    				id:'hidden2_MP_ID',
                    				value:''
                    			}
                    			,{
                    				//用于存放maifield MP_ID
                    				xtype:'hiddenfield',
                    				id:'HIS_COUNT',
                    				value:''
                    			},{
                    				//用于存放maifield MP_ID
                    				xtype:'hiddenfield',
                    				id:'CURR_COUNT',
                    				value:''
                    			},{
                    				//用于存放选择哪一个项目的下biao
                    				xtype:'hiddenfield',
                    				id:'store_index',
                    				value:''
                    			},
                    			{
                    				//用于存放选工号最新启动次数
                    				xtype:'hiddenfield',
                    				id:'CURR_COUNT_index',
                    				value:''
                    			},
                    			{
                    				//日滨返回时用，记录时间
                    				xtype:'hiddenfield',
                    				id:'MaintainTime',
                    			},
                    			{
                    				//电梯激活状态
                    				xtype:'hiddenfield',
                    				id:'ISACTIVE',
                    			},
                    			{
                    				//维保类型
                    				xtype:'hiddenfield',
                    				id:'TASK_NAME',
                    			},
//                    			{
//                    				//梯种
//                    				xtype:'hiddenfield',
//                    				id:'ELEVATOR_TYPE',
//                    			},
                    			{
                    				//MP_ID
                    				xtype:'hiddenfield',
                    				id:'MP_ID',
                    			},
                    			{
                    				//保养计划状态
                    				xtype:'hiddenfield',
                    				id:'PLAN_STATUS_N',
                    			},
                    			{
                    				//REF_ACTIVITYTIMES
                    				xtype:'hiddenfield',
                    				id:'REF_ACTIVITYTIMES',
                    			},
                    			{
                    				//REF_TEMPLATEID
                    				xtype:'hiddenfield',
                    				id:'REF_TEMPLATEID',
                    			},

                    			{
                                    xtype: 'fieldset',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            label: '合同编码',
                                            labelWidth: '50%',
                                            id:'AGREE_NUM',
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '工号编码',
                                            id:'ASSET_NUM',
                                            labelWidth: '50%',
                                            value: [
                                                
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '计划人员1',
                                            labelWidth: '50%',
                                            id:'PLAN_EMP_ID1',
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '计划人员2',
                                            labelWidth: '50%',
                                            id:'PLAN_EMP_ID2',
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '计划人员3',
                                            id:'PLAN_EMP_ID3',
                                            labelWidth: '50%',
//                                            hidden:true,
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '计划年',
                                            id:'PLAN_YEAR',
                                            labelWidth: '50%',
                                            hidden:true,
                                            value: [
                                              
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '计划月',
                                            id:'PLAN_MONTH',
                                            hidden:true,
                                            labelWidth: '50%',
                                            value: [
                                              
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '计划周',
                                            id:'PLAN_WEEK',
                                            hidden:true,
                                            labelWidth: '50%',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '次数',
                                            id:'PLAN_TIMES',
                                            labelWidth: '50%',
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '是否延长',
                                            labelWidth: '50%',
                                            id:'DEFER_FLAG',
                                            hidden:true,
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '计划类型',
                                            id:'PLAN_TYPE',
                                            labelWidth: '50%',
                                            hidden:true,
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '所需工具',
                                            id:'PLAN_TOOLS',
                                            hidden:true,
                                            labelWidth: '50%',
                                            value: [
                                               
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '地盘名称',
                                            labelWidth: '50%',
                                            id:'DOMAIN_NAME',
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '大楼名称',
                                            labelWidth: '50%',
                                            id:'EDIFICE_NAME',
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '梯号',
                                            id:'ELEVATOR_MARK',
                                            labelWidth: '50%',
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '梯种',
                                            id:'ELEVATOR_TYPE',
                                            labelWidth: '50%',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '开始时间',
                                            labelWidth: '50%',
                                            id:'PLAN_START_DT',
                                            value: [
                                            ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '时长(分钟)',
                                            labelWidth: '50%',
                                            hidden:true,
                                            id:'STD_TIME',
                                            value:[
                                                   ],
                                            readOnly: true
                                        },   {
                                            xtype: 'textfield',
                                            label: '结束时间',
                                            id:'PLAN_END_DT',
                                            labelWidth: '50%',
                                            value:[
                                                   ],
                                            readOnly: true
                                        }, {
                                            xtype: 'textfield',
                                            label: '客户要求',
                                            id:'ACCNT_REQUEST',
                                            labelWidth: '50%',
                                            value:[
                                                   ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '修正说明',
                                            id:'PLAN_UPDATE_NOTE',
                                            hidden:true,
                                            labelWidth: '50%',
                                            value:[
                                                   ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '备注',
                                            id:'PLAN_REMARK',
                                            hidden:true,
                                            labelWidth: '50%',
                                            value:[
                                                   ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '所属司',
                                            labelWidth: '50%',
                                            id:'COMPANY_NAME',
                                            value:[
                                                   ],
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            label: '所属站',
                                            labelWidth: '50%',
                                            id:'STATION_NAME',
                                            value:[
                                                   ],
                                            readOnly: true
                                        },{
                                            xtype: 'textfield',
                                            label: '所属片',
                                            id:'AREA_NAME',
                                            labelWidth: '50%',
                                            value:[
                                                   ],
                                            readOnly: true
                                        },{
                                            xtype: 'textfield',
                                            label: '所属组',
                                            id:'GROUP_NAME',
                                            labelWidth: '50%',
                                            value:[
                                                   ],
                                            readOnly: true
                                        },{
                                            xtype: 'textfield',
                                            label: '计划状态',
                                            id:'PLAN_STATUS',
                                            labelWidth: '50%',
                                            value:[
                                             ],
                                            readOnly: true
                                        },
                                        
                                       
                                    ]
                                }
                            ]
                        }
                    ]
                }
                ]
            }
        ]
    },
    initialize : function() {
    	//为保养项目列表增加左滑显示按钮 开始 czq
    	Ext.getCmp('maintenacePej').setPlugins(
                [
                    {
                        xclass: 'plugin.SlideActions',
                        openPosition: 130,
                        buttons:[
                             {
                                xtype: 'button',
                                baseCls: 'x-button helcpda-list-button helcpda-bgColor-blue',
                                text: '选择抱闸测量表',
                                initial:function(button) {
                                	if(!(button.record.data.XCNAME_DISPLAY == '' 
                                		&& button.record.data.TASKNAME_DISPLAY != ''
                                		&& button.record.data.TASK_TYPE == '抱闸解体测量表')){
                                		if(button.setHidden){
                                			button.setHidden(true);
                                		}else{
                                			button.hidden = true;
                                		}
                                	}else{
                                		if(button.setHidden){
                                			button.setHidden(false);
                                		}else{
                                			button.hidden = false;
                                		}
                                	}
                                },
                                listeners: {
                                    tap: function(button, e){
                                        e.stopPropagation();
                                        return false;
                                    },
                                    scope: this
                                },
                                handler: function(button, e) {
                                    Ext.getCmp('maintenacePej').fireEvent('hide');
                                    console.log(button.getRecord());
                                    var v_MeasureProject_Id = Ext.getCmp('MP_ID').getValue();
                                    //测试用hardcode的值
//                                    v_MeasureProject_Id = '1-S1Q053';
                                    var v_MeasureItem_ReCheckPerson_Id = button.getRecord().data.ID;
                                    
                                    var getResult = function(res){
                                    	var resp = res.BrakeQuery_Output;
                                    	var v_data = [];
                                    	
                                    	if(resp.NumOutputObjects > 0){
                                    		if(Ext.getCmp('Overlay_Brake')){
                                    			Ext.getCmp('Overlay_Brake').destroy();
                                    		}
                                    		var ol_brake = Ext.Viewport.add(Ext.create('HelcPDA.view.maintain.Overlay_Brake'));
                                    		ol_brake.show();
                                    		
                                    		Ext.getCmp('H_Brake_Index').setValue(Ext.getCmp('maintenacePej').getStore().find('ID',button.getRecord().data.ID));
                                    		Ext.getCmp('L_Brake').getStore().removeAll(true);
                                    		var respo = resp.ListOfHelPdaMaintainingPlanBrakeMeasurePicklistIo.HelMaintainingPlanActionTaskBz;
                                    		if(respo.length){
                                    			for(var i = 0;i < respo.length;i++){
                                    				v_data.push({
                                    					ActivityId:respo[i].ActivityId,
                                    					Id:respo[i].Id,
                                    					MeasureItemReCheckPersonId:respo[i].MeasureItemReCheckPersonId,
                                    					MeasureProjectId:respo[i].MeasureProjectId,
                                    					TaskDescription:respo[i].TaskDescription,
                                    					TaskName:respo[i].TaskName,
                                    				});
                                    			}
                                    		}else{
                                    			v_data.push({
                                    				ActivityId:respo.ActivityId,
                                    				Id:respo.Id,
                                    				MeasureItemReCheckPersonId:respo.MeasureItemReCheckPersonId,
                                    				MeasureProjectId:respo.MeasureProjectId,
                                    				TaskDescription:respo.TaskDescription,
                                    				TaskName:respo.TaskName,
                                    			});
                                    		}
                                    		
                                    		Ext.getCmp('L_Brake').getStore().setData(v_data);
                                    	}else{
                                    		Ext.toast('无可用选项！',2000);
                                    	}
                                    }

                                    var parameters = {
                                    	procedure : 'BrakeQuery',
                                    	isLoading : true,
                                    	MeasureProject_Id : v_MeasureProject_Id,
                                    	MeasureItem_ReCheckPerson_Id : v_MeasureItem_ReCheckPerson_Id,
                                    };
                                    					
                                    MainCtr.getDataFromServer(getResult,parameters);
                                }
                            }
                        ]
                    }
                ]
            );
    	//为保养项目列表增加左滑显示按钮 结束 czq
    	
    	
    	var tid=Ext.getCmp('hidden2MP_ID').getValue();
    	console.log('tid:'+tid);
        //保养项目list

		//左右滑动页签
		var ITF_tab = Ext.getCmp('mTab'); 
		//左右滑动页签
		var i =0;
		/*与保养项目列表左滑显示按钮冲突，屏蔽 czq
		Ext.get('mTab').on('swipe',function(e,t){
			
			if (e.direction === 'left' && e.distance >= 20) {
				ITF_tab.setActiveItem(ITF_tab.innerItems[i+1]);
				if(i==ITF_tab.innerItems.length-1){
				}else{
					i++;
				}
		    } else if (e.direction === 'right' && e.distance >= 20) {
		    	ITF_tab.setActiveItem(ITF_tab.innerItems[i-1]);
		    	if(i==0){
		    	}else{
		    		i--;
		    	}
		    }
		});
		
		ITF_tab.addListener('activeitemchange',function(obj,value,oldValue,eOpts  ){
			var itemId = value.id;
			if (itemId == 'mC_1') {
				i=0;
			}else if (itemId == 'mC_2') {
				i=1;
			}else if (itemId == 'mC_3') {
				i=2;
			}
			else{
				
			}
		},this,{
		});
		*/
		
	    var query={tid:tid};
	    WL.JSONStore.get(collectionName).find(query).then(function(res){
	    	 var MaintList=Ext.data.StoreManager.get('MaintenaceProtectPrjectStore'); 
	         console.log("ss"+JSON.stringify(res));
	         var stexts=res[0].json.stext;
	         console.log(stexts);
	         console.log(stexts.MP_ID);
	         
	         //alert(12);
	         //alert(stexts.CURR_COUNT);
	         //用于存放选工号最新启动次数
	         Ext.getCmp('CURR_COUNT_index').setValue(stexts.CURR_COUNT);
	         
	         
		     getElementAndSet(res[0].json.tcode,'hidden2_Tcode');//设置隐藏tcode
		     //设置查看数据资料
		     getElementAndSet(stexts.AgreementNumber,'AGREE_NUM');  
		     getElementAndSet(stexts.AssetNumber,'ASSET_NUM');
		     getElementAndSet(stexts.Employee1,'PLAN_EMP_ID1');
		     getElementAndSet(stexts.Employee2,'PLAN_EMP_ID2');
		     getElementAndSet(stexts.Employee3,'PLAN_EMP_ID3');
		     getElementAndSet(stexts.PlanYear,'PLAN_YEAR');
		     getElementAndSet(stexts.PlanMonth,'PLAN_MONTH');
		     getElementAndSet(stexts.PlanWeek,'PLAN_WEEK');
		     getElementAndSet(stexts.PlanTimes,'PLAN_TIMES');
		     getElementAndSet(stexts.PlanTools,'PLAN_TOOLS');
		     
		     getElementAndSet(stexts.DomainName,'DOMAIN_NAME');
		     getElementAndSet(stexts.EdificeName,'EDIFICE_NAME');
		     getElementAndSet(stexts.ELEVATOR_MARK,'ELEVATOR_MARK');
		     //梯号
		     
		     getElementAndSet(stexts.DEFER_FLAG,'DEFER_FLAG');
		     getElementAndSet(stexts.Type,'PLAN_TYPE');
		     
		     getElementAndSet(Ext.Date.format(new Date(stexts.PlanStartDate),'Y-m-d H:i'),'PLAN_START_DT');
		     getElementAndSet(stexts.StandardTimeCalc,'STD_TIME');
		     getElementAndSet(Ext.Date.format(new Date(stexts.PlanEndDate),'Y-m-d H:i'),'PLAN_END_DT');
		     
		     
		     getElementAndSet(stexts.AcountRequest,'ACCNT_REQUEST');
		     getElementAndSet(stexts.OtherComments,'PLAN_UPDATE_NOTE');
		     getElementAndSet(stexts.Remark,'PLAN_REMARK');
		     
		     getElementAndSet(stexts.HoldDivisionName,'COMPANY_NAME');
		     getElementAndSet(stexts.HoldStationName,'STATION_NAME');
		     getElementAndSet(stexts.AreaName,'AREA_NAME');
		     getElementAndSet(stexts.GroupName1,'GROUP_NAME');
		     getElementAndSet(stexts.PlanStatus,'PLAN_STATUS');
		     
		     getElementAndSet(stexts.HIS_COUNT,'HIS_COUNT');
		     getElementAndSet(stexts.CURR_COUNT,'CURR_COUNT');
	          
		     //维保类型 0719
		     //getElementAndSet(stexts.TASK_NAME,'TASK_NAME');
		     getElementAndSet(stexts.ProductCategory,'ELEVATOR_TYPE');
		     getElementAndSet(stexts.Id,'MP_ID');
		     
		     getElementAndSet(stexts.RefActivityTimes,'REF_ACTIVITYTIMES');
		     getElementAndSet(stexts.RefTemplateId,'REF_TEMPLATEID');
		   
		     //end
        	        	
        	        	     
        	        	     //设置实际工作人员
        	        	     /*
        	        	     var ops=stexts.PERSON_NAME;
        	                 var opd=stexts.PERSON_ID;
        	                 var opsz=ops.split("-");
        	                 var opdz=opd.split("=");
        	        	     opsz.push('请选择人员');   	  //添加请选择人员
        	        	     opdz.push('');
        	        	     var data=sortUser(opsz,opdz);
        	        	     
        	        	     Ext.getCmp('ACTUAL_EMP_ID1').setOptions(eval(data));
        	        	     Ext.getCmp('ACTUAL_EMP_ID2').setOptions(eval(data));
        	        	     Ext.getCmp('ACTUAL_EMP_ID3').setOptions(eval(data));
        	        	     
        	        	     */
		     
		     /*
    	      * 独立一
    	      */
    	     var getResult = function(res){
    	    	 var resp = res.MPlanPersonQuery_Output;
    	    	 var persons = [];
    	    	 if(resp.NumOutputObjects > 0){
    	    		 for(var i = 0;i<resp.NumOutputObjects;i++){
    	    			 persons.push({
    	    				 text:resp.ListOfHelPdaMaintainingPlanPersonPicklistIo.Person[i].FullName,
    	    				 value:resp.ListOfHelPdaMaintainingPlanPersonPicklistIo.Person[i].Id,
    	    			 });
    	    		 }
    	    		 persons.sort(function(a,b){
    	    			 return a.text.localeCompare(b.text)
    	    		});
//        	        	    		 persons.sort();
    	    	 }
    	    	 console.log(persons);
    	    	 persons.unshift({text:"请选择",value:""})
    	    	 Ext.getCmp('ACTUAL_EMP_ID1').setOptions(persons);
        	     Ext.getCmp('ACTUAL_EMP_ID2').setOptions(persons);
        	     Ext.getCmp('ACTUAL_EMP_ID3').setOptions(persons);
        	     
        	     setActulPerson(stexts,stexts.ActualEmployeeId1,stexts.ActualEmployeeId2,stexts.ActualEmployeeId3,0);
    	     }
    	     
    	     var parameters = {
    	    		 procedure : 'MPlanPersonQuery',
    	    		 isLoading : true,
    	    		 Company_Id : stexts.HoldDivisionId,
    	    		 Station_Id : stexts.HoldStationId,
    	     };
    	     
    	     MainCtr.getDataFromServer(getResult,parameters);
        	        	     
    	     /*
    	      * 独立二
    	      */
    	     var getResult = function(res){
    	    	 var resp = res.ActionTaskQuery_Output;
    	    	 var data = [];
    	    	 var dataMuCe = [];
    	    	 if(resp.NumOutputObjects > 0){
    	    		 var respo = resp.ListOfHelPdaMaintainingPlanActionTaskListIo.ListOfHelMaintainingPlanActionTask.HelMaintainingPlanActionTask;
    	    		 var v_data;
    	    		 var v_isMUG3;
    	    		 var v_isMuCe;
    	    		 if(respo.length){
    	    			 for(var i = 0;i < resp.NumOutputObjects;i++){
    	    				 v_data = respo[i];
    	    				 v_isMUG3 = v_data.XCNameDisplay=='' && v_data.TaskNameDisplay==''?'Y':'N';
    	    				 v_isMuCe = v_data.TaskNameDisplay==''?'Y':'N';
    	    				 if(v_isMuCe == 'Y'){
    	    					 dataMuCe.push({
    	    						 TASK_NAME:v_isMUG3 == 'Y'?v_data.MUG3TaskName:v_data.TaskName,
	        	    				 PLAN_STATUS:v_data.TaskStatus,
	        	    				 TASK_DESCRIPTION:v_isMUG3 == 'Y'?v_data.MUG3TaskNameDisplay:v_data.TaskDescription,
	        	    				 TASK_ROW_ID:v_data.Id,
	        	    				 PLAN_TIMES:v_isMUG3 == 'Y'?v_data.MUG3StandardTimeCalc:v_data.StandardTimeCalc2,
	        	    				 IS_MUG3:v_isMUG3,
	        	    				 XCNAME_DISPLAY:v_data.XCNameDisplay,
	        	    				 TASKNAME_DISPLAY:v_data.TaskNameDisplay,
	        	    				 TASK_TYPE:v_data.TaskType,
	        	    				 ID:v_data.Id,
	        	    				 TemplateTaskSubId:v_data.TemplateTaskSubId,
    	    					 });
    	    				 }else{
    	    					 data.push({
    	    						 TASK_NAME:v_isMUG3 == 'Y'?v_data.MUG3TaskName:v_data.TaskName,
	        	    				 PLAN_STATUS:v_data.TaskStatus,
	        	    				 TASK_DESCRIPTION:v_isMUG3 == 'Y'?v_data.MUG3TaskNameDisplay:v_data.TaskDescription,
	        	    				 TASK_ROW_ID:v_data.Id,
	        	    				 PLAN_TIMES:v_isMUG3 == 'Y'?v_data.MUG3StandardTimeCalc:v_data.StandardTimeCalc2,
	        	    				 IS_MUG3:v_isMUG3,
	        	    				 XCNAME_DISPLAY:v_data.XCNameDisplay,
	        	    				 TASKNAME_DISPLAY:v_data.TaskNameDisplay,
	        	    				 TASK_TYPE:v_data.TaskType,
	        	    				 ID:v_data.Id,
	        	    				 TemplateTaskSubId:v_data.TemplateTaskSubId,
    	    					 });
    	    				 }
    	    			 }
    	    		 }else{
    	    			 v_data = respo;
    	    			 v_isMUG3 = v_data.XCNameDisplay=='' && v_data.TaskNameDisplay==''?'Y':'N';
	    				 v_isMuCe = v_data.TaskNameDisplay==''?'Y':'N';
	    				 if(v_isMuCe == 'Y'){
	    					 dataMuCe.push({
	    						 TASK_NAME:v_isMUG3 == 'Y'?v_data.MUG3TaskName:v_data.TaskName,
        	    				 PLAN_STATUS:v_data.TaskStatus,
        	    				 TASK_DESCRIPTION:v_isMUG3 == 'Y'?v_data.MUG3TaskNameDisplay:v_data.TaskDescription,
        	    				 TASK_ROW_ID:v_data.Id,
        	    				 PLAN_TIMES:v_isMUG3 == 'Y'?v_data.MUG3StandardTimeCalc:v_data.StandardTimeCalc2,
        	    				 IS_MUG3:v_isMUG3,
        	    				 XCNAME_DISPLAY:v_data.XCNameDisplay,
        	    				 TASKNAME_DISPLAY:v_data.TaskNameDisplay,
        	    				 TASK_TYPE:v_data.TaskType,
        	    				 ID:v_data.Id,
        	    				 TemplateTaskSubId:v_data.TemplateTaskSubId,
	    					 });
	    				 }else{
	    					 data.push({
	    						 TASK_NAME:v_isMUG3 == 'Y'?v_data.MUG3TaskName:v_data.TaskName,
        	    				 PLAN_STATUS:v_data.TaskStatus,
        	    				 TASK_DESCRIPTION:v_isMUG3 == 'Y'?v_data.MUG3TaskNameDisplay:v_data.TaskDescription,
        	    				 TASK_ROW_ID:v_data.Id,
        	    				 PLAN_TIMES:v_isMUG3 == 'Y'?v_data.MUG3StandardTimeCalc:v_data.StandardTimeCalc2,
        	    				 IS_MUG3:v_isMUG3,
        	    				 XCNAME_DISPLAY:v_data.XCNameDisplay,
        	    				 TASKNAME_DISPLAY:v_data.TaskNameDisplay,
        	    				 TASK_TYPE:v_data.TaskType,
        	    				 ID:v_data.Id,
        	    				 TemplateTaskSubId:v_data.TemplateTaskSubId,
	    					 });
	    				 }
    	    		 }
    	    	 }
    	    	 Ext.getCmp('maintenacePej').getStore().setData(data);
    	    	 Ext.getCmp('maintenacePej_MuCe').getStore().setData(dataMuCe);
    	     }
        	        	
    	     /**
    	      * 独立三
    	      */
    	     var parameters = {
    	    		 procedure : 'ActionTaskQuery',
    	    		 isLoading : true,
    	    		 Activity_Id : stexts.ActivityId,
    	     };
    	     
    	     MainCtr.getDataFromServer(getResult,parameters);
             //覆盖原来的数据，使用保存过后的数据
//        	 setItemList(stexts);
    	     //判定年检时间是否可填写
//        	 setYearCheck(stexts.GOV_CHECK_TIME,stexts.INSPECT_YEAR,0,0);
    	     //查看状态是否为已提交，和正在提交中，如果是，就屏蔽
    	     if(stexts.PlanStatus=="已提交"||stexts.PlanStatus=='正在等待提交'||stexts.PlanStatus=="已完成"){
    	    	 Ext.getCmp('ACTUAL_EMP_ID1').setDisabled(true);
    	    	 Ext.getCmp('ACTUAL_EMP_ID2').setDisabled(true);
    	    	 Ext.getCmp('ACTUAL_EMP_ID3').setDisabled(true);
    	    	 Ext.getCmp('ACTUAL_START_DT').setDisabled(true);
    	    	 Ext.getCmp('ACTUAL_END_DT').setDisabled(true);
//        	        	    	 Ext.getCmp('GOV_CHECK_TIME').setDisabled(true);
    	    	 Ext.getCmp('TRAFFIC_TIME').setDisabled(true);
    	    	 Ext.getCmp('ACTUAL_START_DT').setDisabled(true);
//        	        	    	 Ext.getCmp('COMMENTS').setDisabled(true);
//                                 Ext.getCmp('take_picture').setDisabled(true);
//                                 Ext.getCmp('see_picture').setDisabled(true);
                 Ext.getCmp('DetailPanel').disable();
                
    	     }
    	     console.log('---czq');
    	     console.log(res[0].json);
    	     
    	     getElementAndSet(res[0].json.tcode,'hidden2_Tcode');
    	     getElementAndSet(res[0].json.tid,'hidden2_Tid');
        	 getElementAndSet(res[0].json.stext.Id+"--"+Ext.Date.format(new Date(res[0].json.stext.PlanStartDate),'Y-m-d'),'hidden2_MP_ID');//设置隐藏tcode
        	
             
        	 /**
              * 独立四
              */           	 
	    	 var store=Ext.data.StoreManager.get('MaintenacePictureStore');
	    	 if (!store) { 
	    		 store = Ext.create('HelcPDA.model.maintain.MaintenacePictureModel'); 
	    	 }; 
             var query1={tcode:(res[0].json.tid+"_Value")};
             WL.JSONStore.get(collectionName).find(query1).then(function(rest){
            	//console.log('--------------独立四');
            	//console.log(rest[0].json.stext);
            	if(!(typeof(rest[0])=="undefined")){
    		    	var stext=rest[0].json.stext;
    		 	    //设置照片
    		    	picture_list=rest[0].json.files; 
    		 	    var length=picture_list.length;
 			        Ext.getCmp('picture_listV').setHeight(length==0?0:(length+1)*35);
     		         store.setData(picture_list);
 			         //设置结束
	        	     getElementAndSet(rest[0].json.tcode,'hidden2_Tcode');//设置隐藏tcode
            	      //对实际作业人员进行覆盖
	        	     setActulPerson(stext,stext.ACTUAL_EMP_ID1,stext.ACTUAL_EMP_ID2,stext.ACTUAL_EMP_ID3);  
             	      //对保养项目进行初始化
            	     setItemList(stext);
                 	 getElementAndSet(rest[0].json.tid,'hidden2_Tid');
    		    } else{
    		    	picture_list=[];
    		    	store.setData();
    		    }
            }).fail(function(){
            	
            });	
                      
	    	/**
	    	 * 独立五
	    	 */
	    	function setItemList(stexts){
	             var  queryForItem={tid:stexts.MP_ID+"/",tcode:"MAINITEM"};
	        	 WL.JSONStore.get(collectionName).find(queryForItem).then(function(res){
	        		 var length=res.length;
	        		 var tempArray=new Array();
	        		 for(var i=0;i<length;i++){
	        			 var stextz= res[i].json.stext;
	        			 tempArray.push(stextz);
	        			 if(stextz.TASK_NAME.indexOf('半月')!=-1){
	        				 Ext.getCmp('TASK_NAME').setValue('半月');
	        			 }else if(stextz.TASK_NAME.indexOf('季度')!=-1){
	        				 Ext.getCmp('TASK_NAME').setValue('季度');
	        			 }else if(stextz.TASK_NAME.indexOf('半年')!=-1){
	        				 Ext.getCmp('TASK_NAME').setValue('半年');
	        			 }else if(stextz.TASK_NAME.indexOf('年度')!=-1){
	        				 Ext.getCmp('TASK_NAME').setValue('年度');
	        			 }
	        		 }
	        		 
	         	     if (!MaintList) { 
	         	    	 MaintList = Ext.create("HelcPDA.store.maintain.MaintenaceProtectPrjectStore"); 
	         	     };
	         	     Ext.getCmp('maintenacePej').setStore(MaintList);
	         	     MaintList.setData(tempArray);
	         	     Ext.getCmp('hidden2Task_row_Id').setValue(res[0].json.stext.TASK_ROW_ID==undefined?'':res[0].json.stext.TASK_ROW_ID);
	         	     Ext.getCmp('hidden2_stext_MP_ID').setValue(stexts.MP_ID);
	         	     Ext.getCmp('hidden2_maintem_Tid').setValue(res[0].json.tid==undefined?'':res[0].json.tid);
	        	  }).fail(function(err){
	        		  WL.Toast.show("查找items失败");
	        	  });
	    	};
	    	
	    	
	    	/**
	    	 * 独立六	
	    	 */
	    	//判定是否可以设置年检日期
	    	function  setYearCheck(strCheckYear,strPCheckYear,month,day){
	    		var nowYear=new Date().getFullYear();
	    		if(strCheckYear!=''&&strCheckYear!=null&&typeof(strCheckYear)!='undefined'){
	    			strCheckYear=new Date(strCheckYear).getFullYear();
	    		}
				//alert("年检时间:"+strCheckYear+"        今年实际年份:"+nowYear+"   计划年检时间: "+strPCheckYear);
				if(typeof(strCheckYear)!='undefined'&&parseInt(strCheckYear)>=parseInt(nowYear)){
						Ext.getCmp('GOV_CHECK_TIME').setValue('');
						Ext.getCmp('GOV_CHECK_TIME').setDisabled(true);
						//WL.Toast.show("年检时间不可填写");
				}else if((typeof(strCheckYear)=='undefined'||parseInt(strCheckYear)==(parseInt(nowYear)-1))&&parseInt(strPCheckYear)==parseInt(nowYear)){
					Ext.getCmp('GOV_CHECK_TIME').setValue('');
					Ext.getCmp('GOV_CHECK_TIME').setDisabled(false);
					//WL.Toast.show("年检时间必填");
				}else{
					Ext.getCmp('GOV_CHECK_TIME').setValue('');
					Ext.getCmp('GOV_CHECK_TIME').setDisabled(false);
					//WL.Toast.show("年检时间可填写，可不填写");
					//alert("可填写，可不");
				}
	    	};     	    
        	     
	    	function getElementAndSet(relElementName,ElementName){
	    		Ext.getCmp(ElementName).setValue(relElementName);
            }
            	
	    	function setOptions(ElementName,StoreName){
	    		Ext.getCmp(ElementName).setOptions(StoreName);        		
     	    }
        	    
	    	function setActulPerson(stext,pe1,pe2,pe3,num){
	    		//判定是否覆盖计划时间
	    		if(num==0){
		           getElementAndSet(Ext.Date.format(new Date(stext.PlanStartDate),'Y-m-d H:i'),'ACTUAL_START_DT');
		           getElementAndSet(Ext.Date.format(new Date(stext.PlanEndDate),'Y-m-d H:i'),'ACTUAL_END_DT');
		           RealTimeCompare(stext.PlanStartDate,stext.PlanEndDate);
	    		}else{
		           getElementAndSet(Ext.Date.format(new Date(stext.MaintainStartDate),'Y-m-d H:i'),'ACTUAL_START_DT');
		           getElementAndSet(Ext.Date.format(new Date(stext.MaintainEndDate),'Y-m-d H:i'),'ACTUAL_END_DT');
		           RealTimeCompare(stext.MaintainStartDate,stext.MaintainEndDate);
	    		}
	    		//设置实际时长
	    		//设置年检时间  交通时间 备注
	    		/*
		      	if(stext.GOV_CHECK_TIME==''||stext.GOV_CHECK_TIME==null||typeof(stext.GOV_CHECK_TIME)=='undefined'){
		    	  	Ext.getCmp('GOV_CHECK_TIME').setValue(); 
		      	}else{
		    	  	Ext.getCmp('GOV_CHECK_TIME').setValue(Ext.Date.format(new Date(stext.GOV_CHECK_TIME),'Y-m-d')); 
		      	}
	    		 */
	    		getElementAndSet(stext.TrafficTime,'TRAFFIC_TIME');
	    		getElementAndSet(stext.Remark,'PLAN_REMARK');
	    		//设置实际作业人员     	
	    		Ext.getCmp('ACTUAL_EMP_ID1').setValue(pe1);
	    		Ext.getCmp('ACTUAL_EMP_ID2').setValue(pe2);
	    		Ext.getCmp('ACTUAL_EMP_ID3').setValue(pe3);
	    		getElementAndSet(stext.PlanStatus,'PLAN_STATUS');//覆盖状态
            }; 
	    
	    }).fail(function(err){
	    	WL.Toast.show("查找出错");
	    });
    }
    
});

function sortUser(arr,arr1){
      var	data="[";
      		for(var i=0;i<arr.length;i++){
      			if(i!=arr.length-1){
      				data+="{'value':'"
	    	        		 +arr1[i]+"','text':'"+arr[i]+"'},";
      			}else{
      				data+="{'value':'"
	    	        		 +arr1[i]+"','text':'"+arr[i]+"'}";
      			}
      		}
      	data+="]";
      	return data;
      }
function RealTimeCompare(beginTime,endTime){
	
	 var tempBgT=new Date(beginTime);
	 var tempEndT=new Date(endTime);

	 //zhj
	 var tempNumBT=tempBgT.getTime();
	 var tempNumET=tempEndT.getTime();
	 //var tempNumBT=Date.UTC(tempBgT.getFullYear(),(tempBgT.getMonth()+1),tempBgT.getDate(),tempBgT.getHours()==0?24:tempBgT.getHours(),tempBgT.getMinutes());
	 //var tempNumET=Date.UTC(tempEndT.getFullYear(),(tempEndT.getMonth()+1),tempEndT.getDate(),tempEndT.getHours()==0?24:tempEndT.getHours(),tempEndT.getMinutes());

	 var NearlyTime=(tempNumET-tempNumBT)/3600/1000;
	 
	 
	
	 
	 
	 console.log("tempBgT:"+tempBgT+"tempEndT:"+tempEndT+"tempNumBT:"+tempNumBT+"tempNumET:"+tempNumET+"NearlyTime:"+NearlyTime+"zhazha"+tempBgT.getTime()+"zhazha1"+tempEndT.getTime());
//	 var NearlyTime=(Date.parse(new Date(endTime))-Date.parse(new Date(beginTime)))/3600/1000;
	 if(NearlyTime<1){
   	 Ext.getCmp('ACTUAL_Using_Date').setValue(Math.round((NearlyTime*60))+"分钟");
    }
	 else if(NearlyTime>1){
		 var array=NearlyTime.toString().split(".");
		 var length=array.length;
		 if(length>1){
			 Ext.getCmp('ACTUAL_Using_Date').setValue(array[0]+"小时"+Math.round(parseInt((parseFloat('0.'+array[1])*60).toFixed(4)))+"分钟");
		 }else{
			 Ext.getCmp('ACTUAL_Using_Date').setValue(array[0]+"小时");
		 }

	 } else
		 Ext.getCmp('ACTUAL_Using_Date').setValue("1小时");
	 
	 if(Math.round((NearlyTime*60))>720||Math.round((NearlyTime*60))<30){
		 Ext.Msg.alert('提示','输入有误！开始时间与结束时间之差不能小于30min以及不能大于12h！');
		 return;
	 }

 }

