/*
 * File: app/view/MyTabPanel5.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcBPM.view.Main_List', {
    extend: 'Ext.tab.Panel',
    id:'Main_List',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Spacer'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '合同审批',
                items: [
                    {
                        xtype: 'button',
                        id:'btn_INSlist_back',
                        ui: 'back',
                        text: '退出'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'ctn_approvling',
                title: '待审批',
                items: [
                	{
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'searchfield',
                                id: 'sf_INS_approval',
                                width: '100%',
                                placeHolder: '请输入过滤条件',
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        id:'list_INS_approval',
                        store: 'ApproveStore',
                        height: '100%',
                        itemTpl: [
                            '<table align=\'center\' width=\'100%\' border=\'0\' cellpadding=\'0\' cellspacing="0" class="lists-font-size">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>流程：</td><td colSpan=\'3\'>{bpdName}</td>',
                            '</tr>',
                            '<tpl if="appName==\'AZD01\'">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>委托合同号：</td><td width=\'37%\'>{WthtNo}</td><td width=\'18%\'>营分司：</td><td width=\'32%\'>{Yfs}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>工程合同号：</td><td>{GchtNo}</td><td>委托合同类型：</td><td>{WthtType}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>客户：</td><td>{WtClientName}</td><td>工程服务商：</td><td>{Gcfws}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>审批值：</td><td>{Spz}</td><td>委托合同申请版本：</td><td>{WtspVersion}</td>',
                            '</tr>',
                            '</tpl>',
                            '<tpl if="appName==\'WBPJ01\'">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>营分司：</td><td width=\'37%\'>{bmname}</td><td width=\'17%\'>客户：</td><td width=\'33%\'>{BjClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>订单号：</td><td>{BjOrderNo}</td><td>维保大客户：</td><td>{BjWbClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>订单名称：</td><td>{BjOrderName}</td><td>审批浮率：</td><td>{BjSpFl}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>报价版本号：</td><td>{BjBjVersion}</td><td></td><td></td>',
                            '</tr>',
                            '</tpl>',
                            '<tpl if="appName==\'WBWX01\'">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>营分司：</td><td width=\'37%\'>{bmname}</td><td width=\'17%\'>客户：</td><td width=\'33%\'>{BjClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机编号：</td><td>{BjSjNo}</td><td>维保大客户：</td><td>{BjWbClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机名称：</td><td>{BjSjName}</td><td>审批浮率：</td><td>{BjSpFl}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>合同类型：</td><td>{HtType}</td><td>报价版本号：</td><td>{BjVersion}</td>',
                            '</tr>',
                            '</tpl>',
                            '<tpl if="appName==\'WBWG01\'">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>营分司：</td><td width=\'37%\'>{bmname}</td><td width=\'17%\'>客户：</td><td width=\'33%\'>{BjClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机编号：</td><td>{BjSjNo}</td><td>客户类型：</td><td>{ClientType}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机名称：</td><td>{BjSjName}</td><td>审批浮率：</td><td>{SpFl}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>合同类型：</td><td>{HtType}</td><td>报价版本号：</td><td>{BjVersion}</td>',
                            '</tr>',
                            '</tpl>',
                            '</table>'
                        ],
                        
                        onItemDisclosure: true
                    },{
                    	xtype:'hiddenfield',
        				id:'hf_currPagel',
        				value:'1'
                    },
                    {
                    	xtype:'hiddenfield',
        				id:'hf_currPagel_total',
        				value:''
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                id:'btn_INS_prepage_approval',
//                                flex: 1,
                                iconCls: 'arrow_left',
                                text: '上一页'
                            },
                            {
                                xtype: 'spacer',
//                                flex: 1
                            },
                            {
                                xtype: 'container',
                                id: 'ctn_showCurrPagel',
                                html: '当前页数：1'
                            },
                            {
                                xtype: 'spacer',
//                                flex: 1
                            },
                            {
                                xtype: 'button',
                                id:'btn_INS_nextpage_approval',
//                                flex: 1,
                                ui: 'forward',
                                iconAlign: 'right',
                                iconCls: 'arrow_right',
                                text: '下一页'
                            }
                        ]
                    }  
                ]
            },
            {
                xtype: 'container',
                id: 'ctn_approved',
                title: '已审批',
                items: [
                	{
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'searchfield',
                                id: 'sf_INS_approved',
                                width: '100%',
                                placeHolder: '请输入过滤条件',
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        store: 'ApprovedListStore',
                        id:'list_INS_approved',
                        height: '100%',
                        itemTpl: [
                            '<table align=\'center\' width=\'100%\' border=\'0\' cellpadding=\'0\' cellspacing="0" class="lists-font-size">',
                            '<tr height=\'25\'>',
							'<td width=\'13%\'>流程：</td><td colSpan=\'3\'>{BPD_NAME}</td>',
							'</tr>',
							'<tpl if="APP_NAME==\'AZD01\'">',
							'<tr height=\'25\'>',
							'<td width=\'13%\'>委托合同号：</td><td width=\'37%\'>{WTHTNO}</td><td width=\'17%\'>营分司：</td><td width=\'33%\'>{YFS}</td>',
							'</tr>',
							'<tr height=\'25\'>',
							'<td>工程合同号：</td><td>{WTGCHTNO}</td><td>委托合同类型：</td><td>{WTHTTYPE}</td>',
							'</tr>',
							'<tr height=\'25\'>',
							'<td>客户：</td><td>{WTCLIENTNAME}</td><td>工程服务商：</td><td>{GCFWS}</td>',
							'</tr>',
							'<tr height=\'25\'>',
							'<td>审批值：</td><td>{SPZ}</td><td>委托合同申请版本：</td><td>{WTSPVERSION}</td>',
							'</tr>',
							'</tpl>',
							'<tpl if="APP_NAME==\'WBPJ01\'">',
							'<tr height=\'25\'>',
							'<td width=\'13%\'>营分司：</td><td width=\'37%\'>{bmname}</td><td width=\'17%\'>客户：</td><td width=\'33%\'>{BjClientName}</td>',
							'</tr>',
							'<tr height=\'25\'>',
							'<td>订单号：</td><td>{BjOrderNo}</td><td>维保大客户：</td><td>{BjWbClientName}</td>',
							'</tr>',
							'<tr height=\'25\'>',
							'<td>订单名称：</td><td>{BjOrderName}</td><td>审批浮率：</td><td>{BjSpFl}</td>',
							'</tr>',
							'<tr height=\'25\'>',
							'<td>报价版本号：</td><td>{BjBjVersion}</td><td></td><td></td>',
							'</tr>',
							'</tpl>',
							'<tpl if="APP_NAME==\'WBWX01\'">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>营分司：</td><td width=\'37%\'>{bmname}</td><td width=\'17%\'>客户：</td><td width=\'33%\'>{BjClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机编号：</td><td>{BjSjNo}</td><td>维保大客户：</td><td>{BjWbClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机名称：</td><td>{BjSjName}</td><td>审批浮率：</td><td>{BjSpFl}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>合同类型：</td><td>{HtType}</td><td>报价版本号：</td><td>{BjVersion}</td>',
                            '</tr>',
                            '</tpl>',
                            '<tpl if="APP_NAME==\'WBWG01\'">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>营分司：</td><td width=\'37%\'>{bmname}</td><td width=\'17%\'>客户：</td><td width=\'33%\'>{BjClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机编号：</td><td>{BjSjNo}</td><td>客户类型：</td><td>{ClientType}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机名称：</td><td>{BjSjName}</td><td>审批浮率：</td><td>{SpFl}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>合同类型：</td><td>{HtType}</td><td>报价版本号：</td><td>{BjVersion}</td>',
                            '</tr>',
                            '</tpl>',
							'</table>'
                              ],
                        onItemDisclosure: true
                    },{
                    	xtype:'hiddenfield',
        				id:'hf_currPaged',
        				value:'1'
                    },
                    {
                    	xtype:'hiddenfield',
        				id:'hf_currPaged_total',
        				value:''
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                id:'btn_INS_prepage_approved',
//                                flex: 1,
                                iconCls: 'arrow_left',
                                text: '上一页'
                            },
                            {
                                xtype: 'spacer',
//                                flex: 1
                            },
                            {
                                xtype: 'container',
                                id: 'ctn_showCurrPaged',
                                html: '当前页数：1'
                            },
                            {
                                xtype: 'spacer',
//                                flex: 1
                            },
                            {
                                xtype: 'button',
                                id:'btn_INS_nextpage_approved',
//                                flex: 1,
                                ui: 'forward',
                                iconAlign: 'right',
                                iconCls: 'arrow_right',
                                text: '下一页'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'ctn_approve_finish',
                title: '已完成',
                items: [
                	{
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'searchfield',
                                id: 'sf_INS_completed',
                                width: '100%',
                                placeHolder: '请输入过滤条件',
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        id:'list_INS_completed',
                        height: '100%',
                        store: 'ApproveFinishListStore',
                        itemTpl: [
                            '<table align=\'center\' width=\'100%\' border=\'0\' cellpadding=\'0\' cellspacing="0" class="lists-font-size">',
                            '<tr height=\'25\'>',
							'<td width=\'13%\'>流程：</td><td colSpan=\'3\'>{BPD_NAME}</td>',
							'</tr>',
							'<tpl if="APP_NAME==\'AZD01\'">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>委托合同号：</td><td width=\'37%\'>{WTHTNO}</td><td width=\'17%\'>营分司：</td><td width=\'33%\'>{YFS}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>工程合同号：</td><td>{WTGCHTNO}</td><td>委托合同类型：</td><td>{WTHTTYPE}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>客户：</td><td>{WTCLIENTNAME}</td><td>工程服务商：</td><td>{GCFWS}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>审批值：</td><td>{SPZ}</td><td>委托合同申请版本：</td><td>{WTSPVERSION}</td>',
                            '</tr>',
                            '</tpl>',
                            '<tpl if="APP_NAME==\'WBPJ01\'">',
							'<tr height=\'25\'>',
							'<td width=\'13%\'>营分司：</td><td width=\'37%\'>{bmname}</td><td width=\'17%\'>客户：</td><td width=\'33%\'>{BjClientName}</td>',
							'</tr>',
							'<tr height=\'25\'>',
							'<td>订单号：</td><td>{BjOrderNo}</td><td>维保大客户：</td><td>{BjWbClientName}</td>',
							'</tr>',
							'<tr height=\'25\'>',
							'<td>订单名称：</td><td>{BjOrderName}</td><td>审批浮率：</td><td>{BjSpFl}</td>',
							'</tr>',
							'<tr height=\'25\'>',
							'<td>报价版本号：</td><td>{BjBjVersion}</td><td></td><td></td>',
							'</tr>',
							'</tpl>',
							'<tpl if="APP_NAME==\'WBWX01\'">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>营分司：</td><td width=\'37%\'>{bmname}</td><td width=\'17%\'>客户：</td><td width=\'33%\'>{BjClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机编号：</td><td>{BjSjNo}</td><td>维保大客户：</td><td>{BjWbClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机名称：</td><td>{BjSjName}</td><td>审批浮率：</td><td>{BjSpFl}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>合同类型：</td><td>{HtType}</td><td>报价版本号：</td><td>{BjVersion}</td>',
                            '</tr>',
                            '</tpl>',
                            '<tpl if="APP_NAME==\'WBWG01\'">',
                            '<tr height=\'25\'>',
                            '<td width=\'13%\'>营分司：</td><td width=\'37%\'>{bmname}</td><td width=\'17%\'>客户：</td><td width=\'33%\'>{BjClientName}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机编号：</td><td>{BjSjNo}</td><td>客户类型：</td><td>{ClientType}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>商机名称：</td><td>{BjSjName}</td><td>审批浮率：</td><td>{SpFl}</td>',
                            '</tr>',
                            '<tr height=\'25\'>',
                            '<td>合同类型：</td><td>{HtType}</td><td>报价版本号：</td><td>{BjVersion}</td>',
                            '</tr>',
                            '</tpl>',
                            '</table>'
                              ],
                        onItemDisclosure: true
                    },{
                    	xtype:'hiddenfield',
        				id:'hf_currPagef',
        				value:'1'
                    },
                    {
                    	xtype:'hiddenfield',
        				id:'hf_currPagef_total',
        				value:''
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                id:'btn_INS_prepage_completed',
//                                flex: 1,
                                iconCls: 'arrow_left',
                                text: '上一页'
                            },
                            {
                                xtype: 'spacer',
//                                flex: 1
                            },
                            {
                                xtype: 'container',
                                id: 'ctn_showCurrPagef',
                                html: '当前页数：1'
                            },
                            {
                                xtype: 'spacer',
//                                flex: 1
                            },
                            {
                                xtype: 'button',
                                id:'btn_INS_nextpage_completed',
//                                flex: 1,
                                ui: 'forward',
                                iconAlign: 'right',
                                iconCls: 'arrow_right',
                                text: '下一页'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});