Ext.define('HelcPDA.model.install.installcheck.TasksFactoryModel',{
	extend:'Ext.data.Model',
	config:{
		fields:[
		        'TASK_PROCESS_ID','ORG_ID','TASK_ID','ECount',
		        'INT_TASK_ID','INT_TASK_PROCESS_ID','NUM',
		        
		        'SEQ_NUM','DEBUG_NUM','TOEBS_DEBUG_NUM',
		        'CHECK_NUM','TOEBS_CHECK_NUM',
		        'ENGCONTRACT_NUMBER','ELEVATOR_NO',
		        'CUSTOMER_NAME','PROJECT_NAME',
		        'INSTALL_ADDRESS','PRODUCE_TYPE',
		        'EQUIPMENT_NO','CM_ELEVATOR_TYPE_NAME',

		        'ELEVATOR_CLASS_NAME','NST_VENDOR_NAME',
		        'LIFT_VENDOR_NAME','BUILD_VENDOR_NAME',
		        'BUDGET_INSTALL_METHOD',

		        'PARAM_C_Z_M','ZZ','SD','TSGD','JDZG',

		        'GET_CHECK_DATE','PLAN_CHECK_DATE',
		        'INST_PERSON_NAME','PLAN_CHECK_FINISH_DATE',
		        'CHECK_STATUS',

		        'CHECK_APPROVED_BY','CHECK_APPROVAL_DATE',
		        'CHECK_APPROVAL_NOTE','NO_HETONG','NO_GONGHAO',
		        'NO_PICI','NO_CIDI',

		        'CHECK_ARRIVE_DATE',
		        'CHECK_DATE','REPORT_DATE','REPORT_ENTER_DATE',
		        'AHEAD_REPORT_DATE','RE_CHECK_DATE','CHECK_FORFEIT_AMT',
		        'CHECK_FORFEIT_DATE','CHECK_RETURN_FLAG','CHECK_RETURN_DATE',
		        'CHECK_RETURN_REASON','CHECK_TB627','CHECK_TB628',
		        'CHECK_TB629','PROBLEM_ITEM_NUM','RECTIFIED_NUM',
		        'UNRECTIFIED_NUM','PROBLEM_ITEM_DESC','EXTRA_BAD_NUM',
		        'EXTRA_BAD_DECS','PROBLEM_ADD_DESC','BAD_DELIVERY_DATE',
		        'SERVICE_NUM','CHECK_COMMENTS','EBS_FULL_NAME',
		        'CHANG_SATRTUS','JL_NAME','CHECK_NAME','BALANCE_INDEX',
		        'COUNTER_WEIGHT',

		        'DYDL_UP_0','DYDL_UP_30','DYDL_UP_40','DYDL_UP_45',
		        'DYDL_UP_50','DYDL_UP_60','DYDL_UP_100','DYDL_UP_110',
		        'DYDL_DOWN_0','DYDL_DOWN_30','DYDL_DOWN_40','DYDL_DOWN_45',
		        'DYDL_DOWN_50','DYDL_DOWN_60','DYDL_DOWN_100','DYDL_DOWN_110',
		        'DJDL_UP_0','DJDL_UP_30','DJDL_UP_40','DJDL_UP_45',
		        'DJDL_UP_50','DJDL_UP_60','DJDL_UP_100','DJDL_UP_110',
		        'DJDL_DOWN_0','DJDL_DOWN_30','DJDL_DOWN_40','DJDL_DOWN_45',
		        'DJDL_DOWN_50','DJDL_DOWN_60','DJDL_DOWN_100','DJDL_DOWN_110',
		        'PCSJ_UP_0','PCSJ_UP_30','PCSJ_UP_40','PCSJ_UP_45',
		        'PCSJ_UP_50','PCSJ_UP_60','PCSJ_UP_100','PCSJ_UP_110',
		        'PCSJ_DOWN_0','PCSJ_DOWN_30','PCSJ_DOWN_40','PCSJ_DOWN_45',
		        'PCSJ_DOWN_50','PCSJ_DOWN_60','PCSJ_DOWN_100','PCSJ_DOWN_110',
		        'DYDY_UP_0','DYDY_UP_30','DYDY_UP_40','DYDY_UP_45',
		        'DYDY_UP_50','DYDY_UP_60','DYDY_UP_100','DYDY_UP_110',
		        'DYDY_DOWN_0','DYDY_DOWN_30','DYDY_DOWN_40','DYDY_DOWN_45',
		        'DYDY_DOWN_50','DYDY_DOWN_60','DYDY_DOWN_100','DYDY_DOWN_110',
		        
		        'INSTALL_CHECK_START_DATE','INSTALL_CHECK_END_DATE',
		        'RECHECK_START_DATE','RECHECK_FINISH_DATE','PLAN_FINISH_DATE',
		        'CHECK_MAN_SIGN','CHECK_MAN_SIGN_NAME','CHECK_MAN_SIGN1',
		        'CHECK_MAN_SIGN1_NAME','TRANSFER_CUSTOMER_ID','','TRANSFER_CUSTOMER_NAME',
		        
		        'CHECK_ACCEPT_STATUE','TEL1','SUPERVISOR_SIGN1','SUPERVISOR_SIGN1_NAME',
		        'NOT_CREATE_COST','WHETER_APPLY_TO_CUSTOMER','FLG','AGREE_FOLLOWUP',
		        'AGREE_CHECK_ROLLBACK','AGREE_RECHECK_BACKCHECK','PROJECT_PRINCIPAL_SIGN_DATE',
		        'CHECKOUT_PRINCIPAL_SIGN_DATE','SURPERVISOR_SIGN_DATE','CHECKOUT_APPROVE_SIGN_DATE',
		        'CHECK_PRINCIPAL_SIGN_DATE','CHECK_PRINCIPAL_SIGN_TXT','SETUP_UNIT_SIGN_NAME',
		        'SETUP_UNIT_SIGN1_NAME','CHECKOUT_APPROVE_SIGN_NAME','SURPERVISOR_SIGN_NAME',
		        'CHECKOUT_PRINCIPAL_SIGN_NAME','PROJECT_PRINCIPAL_SIGN_NAME','INSTALL_HEADER','TEL'
		        ]
	}
});
