/*
 * File: app/view/Lifecycle/ElevatorDetail.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcRemote.view.Lifecycle.ElevatorDetail', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Panel',
        'Ext.Label',
        'Ext.Button',
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
        id: 'Lifecycle_ElevatorDetail',
        layout: 'vbox',
        items: [
            {
                xtype: 'panel',
                cls: 'remote-breadCrumb',
                docked: 'top',
                items: [
                    {
                        xtype: 'label',
                        cls: 'remote-breadCrumb-con',
                        html: '首屏 > 生命周期 > 生命周期详细',
                        id: 'Lifecycle_ElevatorDetail_title'
                    },
                    {
                        xtype: 'panel',
                        cls: 'remote-breadCrumb-buttonBox',
                        docked: 'right',
                        items: [
                            {
                                xtype: 'button',
                                cls: 'remote-buttonColor-orange',
                                id: 'Lifecycle_Elevator_btnReturn',
                                text: '返回'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                cls: [
                    'remote-content',
                    'remote-home-State'
                ],
                layout: 'vbox',
                items: [
                    {
                        xtype: 'panel',
                        flex: 1,
                        cls: 'remote-service-ChinaMap',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'panel',
                                flex: 1,
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: 'remote-title',
                                        docked: 'top',
                                        items: [
                                            {
                                                xtype: 'label',
                                                cls: 'remote-titleText',
                                                docked: 'left',
                                                html: '生命周期节点'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'dataview',
                                                flex: 1,
                                                cls: 'remote_home-StateBox',
                                                data: [
                                                    {
                                                        node: '合同'
                                                    },
                                                    {
                                                        node: '设计'
                                                    },
                                                    {
                                                        node: '生产'
                                                    },
                                                    {
                                                        node: '安装'
                                                    },
                                                    {
                                                        node: '维保'
                                                    },
                                                    {
                                                        node: '升级改造'
                                                    },
                                                    
                                                ],
                                                id: 'Lifecycle_Elevator_Node',
                                                itemTpl: [
                                                    '<div class="remote-home-State">{node}</div>'
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});