/*
 * File: app/view/Service/monitor_Favorite.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcRemote.view.Service.monitor_Favorite', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Panel',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        id: 'Service_branch_Favorite',
        layout: 'vbox',
        cls: [
            'remote-content',
            'remote-service'
        ],
        items: [
            {
                xtype: 'panel',
                flex: 1,
                cls: 'remote-service-FaultMonitor',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'panel',
                        cls: 'remote-title',
                        items: [
                            {
                                xtype: 'label',
                                cls: 'remote-titleText',
                                docked: 'left',
                                html: '常用展示电梯'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 1,
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'list',
                                flex: 1,
                                cls: 'remote-FaultMonito-listBox',
                                id: 'Service_Monitor_Favorite',
                                itemTpl: [
                                    '<div class="elevator-list">',
                                    '    <div class="elevator-list-left80">{domain_name} - {agree_account_name}</div>',
                                    '    <div class="elevator-list-right20 elevator-type{elevator_type}">{asset_num}</div>',
                                    '</div>'
                                ],
                                store: 'Service_Monitor_Favorite_List'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});