Ext.define('HelcPDA.model.report.maintainbb.KeepAchievementListModel',{
	extend:'Ext.data.Model',
	config:{
		  //公司名称 ，月度预算，月完成率，全年预算,年完成率，总台量
		fields : ['COMPANY_NAME','BUDGET_ALL_BUDGET','BUDGET_ALL_BUDGET_RATE','BUDGET_ALL_BUDGET_QN'
		,'BUDGET_ALL_BUDGET_RATE_QN','NUM',
		
		'CUR_MON_WAR_AMOUNT','REPAIR_BUDGET',
		'REPAIR_BUDGET_RATE','REPAIR_BUDGET_QN',
		'REPAIR_BUDGET_RATE_QN','LST_MON_WAR_AMOUNT','CUR_MON_WAR_STAT_AMOUNT','CUR_MON_WAR_ASS_AMOUNT',
		'CUR_MON_WAR_END_AMOUNT','CUR_MON_WAR_OWN_AMOUNT','CUR_MON_WAR_OTH_AMOUNT',
		'CUR_MON_WAR_LIFT_AMOUNT','CUR_MON_WAR_ESCA_AMOUNT',
		//保养
		'CUR_MON_MAI_AMOUNT','MAINTAINA_BUDGET','MAINTAINA_BUDGET_RATE',
		'MAINTAINA_BUDGET_QN','MAINTAINA_BUDGET_RATE_QN',
		'LST_MON_MAI_AMOUNT','CUR_MON_MAI_PRICE','CUR_MON_MAI_SUM',
		'CUR_MON_MAI_NEW_AMOUNT','CUR_MON_MAI_NEW_PRICE','CUR_MON_MAI_NEW_SUM',
		'CUR_MON_MAI_REN_AMOUNT','CUR_MON_MAI_REN_PRICE','CUR_MON_MAI_REN_SUM',
		'CUR_MON_MAI_RET_PRICE',
		'CUR_MON_MAI_RET_SUM','CUR_MON_MAI_RET_AMOUNT',
		'CUR_MON_MAI_CAN_AMOUNT','CUR_MON_MAI_CAN_PRICE',
		'CUR_MON_MAI_CAN_SUM','CUR_MON_MAI_OWN_AMOUNT',
		'CUR_MON_MAI_OWNED_AMOUNT','CUR_MON_MAI_OTH_AMOUNT',
		'CUR_MON_MAI_OTHED_AMOUNT','CUR_MON_MAI_LIFT_AMOUNT',
		'CUR_MON_MAI_ESCA_AMOUNT'
		
		
		
		]
	}
});