/*
 * File: app/view/CertificatesInfo_C.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPDA.view.certificatesinfo.CertificatesInfo_C', {
	id:'CertificatesInfo_C',
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.TextArea'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '证件详细信息',
                items: [
                    {
                        xtype: 'button',
                        id: 'btn_Back_C',
                        ui: 'back',
                        text: '返回'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: '',
                items: [
                    {
                        xtype: 'textfield',
                        id:'CERT_NAME_CODE',
                        label: '证件名称',
                        labelWidth: '31%',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        id:'CERT_NO',
                        label: '证件号码',
                        labelWidth: '31%',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        id:'CERT_DATE',
                        label: '发证日期',
                        labelWidth: '31%',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        id:'DISABLED_DATE',
                        label: '失效日期',
                        labelWidth: '31%',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        id:'CERT_ORGANIZATION',
                        label: '发证机构',
                        labelWidth: '31%',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        id:'OBJECT_VERSION_NUMBER',
                        label: '记录版本',
                        labelWidth: '31%',
                        readOnly: true
                    },
                    {
                        xtype: 'textareafield',
                        id:'COMMENTS',
                        label: '备注',
                        labelWidth: '31%',
                        readOnly: true
                    }
                ]
            }
        ]
    }

});