/*
 * File: app/view/CertificatesInfo_P.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPDA.view.certificatesinfo.CertificatesInfo_P', {
	id:'CertificatesInfo_P',
    extend: 'Ext.Container',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Text',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '详细信息',
                items: [
                    {
                        xtype: 'button',
                        id: 'btn_Back_P',
                        ui: 'back',
                        text: '返回'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                docked: 'top',
                height: '100%',
                layout: {
                    type: 'card',
                    animation: false
                },
                items: [
                    {
                        xtype: 'formpanel',
                        title: '人员信息',
                        items: [
                            {
                                xtype: 'fieldset',
                                title: '',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id:'PERSON_NAME',
                                        label: '姓名',
                                        labelWidth: '31%',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id:'CERT_NO',
                                        label: '身份证',
                                        labelWidth: '31%',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id:'VENDOR_NAME',
                                        label: '安装单位',
                                        labelWidth: '31%',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id:'WORK_ADDRESS',
                                        label: '工作地',
                                        labelWidth: '31%',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id:'EXPERIENCE_YEAR',
                                        label: '工作年限',
                                        labelWidth: '31%',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id:'JOB_TYPE_CODE',
                                        label: '工种',
                                        labelWidth: '31%',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        id:'JOB_POSITION',
                                        label: '职务',
                                        labelWidth: '31%',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '证件信息',
                        items: [
                            {
                                xtype: 'list',
                                id:'CertPersonC_List',
                                height: '100%',
                                itemTpl: [
                                    '<table border=0 width=100% style="color:#666">',
                					'  <tr height=20>',
                					'        <td width=80%>',
                					'            <span style="color:#000;font-size:18px;">{CERT_NAME_CODE}</span>',
                					'        </td>',
                					'  </tr>',
                					'  <tr>',
                					'		<td width=80%>',
                					'		<span style="color:#000;font-size:15px;">{CERT_NO}</span>',
                					'       </td>',
                					'  </tr>',
                					'  <tr>',
                					'		<td width=80%>',
                					'		<span style="color:#000;font-size:15px;">{CERT_DATE} - {DISABLED_DATE}</span>',
                					'       </td>',
                					'  </tr>',
                					'</table>'
                                ],
                                onItemDisclosure: true,
                                store:'CertPersonC_ListStore',
                            }
                        ]
                    }
                ]
            }
        ]
    }

});