Ext.define('HelcPDA.model.install.installtask.InstallatoinTasksIntaion',{
	extend:'Ext.data.Model',
	config:{
		fields:['ENGCONTRACT_NUMBER','ELEVATOR_NO','CUSTOMER_NAME','INSTALL_ADDRESS','PRODUCE_TYPE','SEQ_NUM',
		        'EQUIPMENT_NO','CM_ELEVATOR_TYPE_NAME','ELEVATOR_CLASS_NAME','dwNAME','dzNAME','dpNAME',
		        'BUDGET_INSTALL_METHOD','PARAM_C','PARAM_Z','PARAM_M','PARAM_ZZ','PARAM_SD','PARAM_TSGD',
		        'PARAM_JDZG','CONTRACT_CYCLE_DAY','DELIVERY_DATE']
	}
});