Ext.define('HelcPDA.model.install.installtask.ZhengFujianModel',{
	extend:'Ext.data.Model',
	id:'ZhengFujianModel',
	config:{
		fields:['ELEVATOR_NO','ENGCONTRACT_NUMBER','PROJECT_NAME','NUM','INSTALL_ADDRESS','PRODUCE_TYPE','EQUIPMENT_NO',
		        'CM_ELEVATOR_TYPE_NAME','ELEVATOR_CLASS_NAME','NST_VENDOR_NAME','LIFT_VENDOR_NAME','BUILD_VENDOR_NAME',
		        'BUDGET_INSTALL_METHOD','PARAM_C_M_Z','ZZ','SD','TSGD','JDZG','CCRQ','PERMIT_USE_NO','sum']
	}
});