/*
 * Licensed Materials - Property of IBM
 * 5725-I43 (C) Copyright IBM Corp. 2006, 2013. All Rights Reserved.
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */
 
#import <Foundation/Foundation.h>

/**
 * This class allows access to risk-assessment data that is generated by Trusteer. <br />
 * To use this class, the Trusteer Mobile SDK must first be installed and integrated with your MobileFirst project.
 */
@interface WLTrusteer : NSObject
/**
 * Provides a WLTrusteer singleton.
 * @returns The shared WLTrusteer object
 */
+(id)sharedInstance;

/**
 * Initializes the Trusteer Mobile SDK that is integrated with the MobileFirst project.
 * <p>
 * <b>Note:</b> This method is applicable only when automatic initialization of the Trusteer Mobile SDK is disabled
 * by setting the TRUSTEER_AUTO_INIT property to <code>false</code> in the client properties file (<b>worklight.plist</b>).
 * </p>
 * @returns The initialized WLTrusteer object
 */
-(id)init;

/**
 * Checks whether the Trusteer Mobile SDK is installed and initialized successfully on the device.
 *  @returns <code>true</code> if the Trusteer Mobile SDK is installed and initialized, or <code>false</code> otherwise
 */
-(BOOL)hasTrusteerSDK;

/**
 * Returns a unique device identifier that is generated by Trusteer.
 * @returns The unique Trusteer device key, or null if the Trusteer Mobile SDK is not installed or was not initialized successfully
 */
-(NSString*)deviceKey;

/**
 * Generates an NSDictionary with all the risk assessments generated by Trusteer. 
 * See the Trusteer documentation for a list of values.
 * @returns Risk-assessments dictionary
 */
-(NSDictionary*)riskAssessment;

/**
 * Generates a JSON string with all the risk assessments generated by Trusteer.
 * See the Trusteer documentation for a list of values.
 * @returns Risk-assessments JSON String
 */
-(NSString*)riskAssessmentAsJson;
@end
