/*
 * File: app/view/MyPanel44.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/**
 * 安装资源录入 xcx
 * 2014-5-5
 */

Ext.define('HelcPDA.view.install.installplan.InstallPlanAZZYLR', {
    extend: 'Ext.Panel',
    id:'installplan_AZZYLR',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.field.DatePicker',
        'Ext.picker.Date'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '安装资源录入',
                items: [
                    {
                        xtype: 'button',
                        id:'installplan_AZZYLR_FHButton',
                        ui: 'back',
                        text: '返回'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'installplan_AZZYLR_TJButton',
                        text: '提交'
                    },
                    {
                    	//用于判断调用了哪个模块的查询按钮
        				xtype:'hiddenfield',
        				id:'installplan_AZZYLR_CXButton_num',
        			},
        			{
        				//吊装工程 人员的集合   
        				xtype:'hiddenfield',
        				id:'installplan_AZZYLR_DZRY_ARRAY',
        			},
        			{
        				//搭棚工程 人员的集合
        				xtype:'hiddenfield',
        				id:'installplan_AZZYLR_DPRY_ARRAY',
        			},
        			{
        				//安装工程 人员的集合
        				xtype:'hiddenfield',
        				id:'installplan_AZZYLR_AZRY_ARRAY',
        			},
        			{
        				//获取批量 资源录入的下标
        				xtype:'hiddenfield',
        				id:'installplan_PLZYLR_FXK_SHUZU',
        			},
        			{
        				//提交时收集的数据（单个/批量）通用
        				xtype:'hiddenfield',
        				id:'installplan_PLZYLR_ZYLR_TRIM',
        			},
                ]
            },
            {
                xtype: 'tabpanel',
                flex: 1,
                items: [
                    {
                        xtype: 'container',
                        title: '吊装工程',
                        height: '100%',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                height: 190,
                                layout: 'vbox',
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'panel',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'searchfield',
                                                        id:'installPlan_AZZYLR_DZGCFWS_JG',
                                                        height: 40,
                                                        width: '90%',
                                                        label: '服务商',
                                                        labelWidth: '42%',
                                                        name: '',
                                                        placeHolder: '请输入搜索关键字'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        id:'installPlan_AZZYLR_DZGCFWS_CXButton',
                                                        height: 41,
                                                        style: 'border:0;',
                                                        width: '10%',
                                                        iconCls: 'search',
                                                        text: ''
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '    ',
                                                id:'installPlan_AZZYLR_DZGCFWS_DZGCFWSGS',
                                                labelWidth: '10%',
                                                /*value: [
                                                    '  广东澳新电梯安装工程有限公司'
                                                ],*/
                                                readOnly: true
                                            },
                                			{//存放公司对应的ID
                                				xtype:'hiddenfield',
                                				id:'installPlan_AZZYLR_DZGCFWS_DZGCFWSGS_hidden',
                                			},
                                            {
                                                xtype: 'selectfield',
                                                id:'installPlanAZLR_DZRY',
                                                label: '吊装人员',
                                                labelWidth: '40%',
                                                placeHolder: '请选择',
                                                usePicker: 'auto'
                                            },
                                            {
                                                xtype: 'container',
                                                margin: '10 15',
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        margin: '',
                                                        id:'installPlanAZZY_AddDZRY',
                                                        text: '增加吊装人员'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'list',
                                flex: 1,
                                store:'InstallAZZYLRStoreThree',
                                id: 'installPlanAZZYLR_DZStore',
                                itemTpl: [
                                    '<table width="100%" border="0" cellspacing="0" cellpadding="0">',
                                    '  <tr>',
                                    '    <td width=91%>{NAMES}</td>',
                                    '	<input type="hidden" name="AZZYLR_DZ_NAMES" value="{IDS}"> ',
                                    '    <td width=9% style="text-align: right;"><img  id="dz" style="width:22px;" src="images/delete01.png"/></td>',
                                    '  </tr>',
                                    '</table>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '搭棚工程',
                        height: '100%',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                height: 190,
                                layout: 'vbox',
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'panel',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'searchfield',
                                                        id:'installPlan_AZZYLR_DPGCFWS_JG',
                                                        height: 40,
                                                        width: '90%',
                                                        label: '服务商',
                                                        labelWidth: '42%',
                                                        name: '',
                                                        placeHolder: '请输入搜索关键字'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        id:'installPlan_AZZYLR_DPGCFWS_CXButton',
                                                        height: 41,
                                                        style: 'border:0;',
                                                        width: '10%',
                                                        iconCls: 'search',
                                                        text: ''
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'textfield',
                                                id:'installPlan_AZZYLR_DPGCFWS_DPGCFWSGS',
                                                label: '  ',
                                                labelWidth: '10%',
                                                /*value: [
                                                    '  广东澳新电梯安装工程有限公司'
                                                ],*/
                                                readOnly: true
                                            },
                                            {//存放公司对应的ID
                                				xtype:'hiddenfield',
                                				id:'installPlan_AZZYLR_DPGCFWS_DPGCFWSGS_hidden',
                                			},
                                            {
                                                xtype: 'selectfield',
                                                id:'installPlanAZLR_DPRY',
                                                label: '搭棚人员',
                                                labelWidth: '40%',
                                                placeHolder: '请选择',
                                                usePicker: 'auto'
                                            },
                                            {
                                                xtype: 'container',
                                                margin: '10 15',
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        id:'installPlanAZZY_AddDPRY',
                                                        margin: '',
                                                        text: '增加搭棚人员'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'list',
                                store:'InstallAZZYLRStoreFour',
                                id: 'installPlanAZZYLR_DPStore',
                                flex: 1,
                                itemTpl: [
                                    '<table width="100%" border="0" cellspacing="0" cellpadding="0">',
                                    '  <tr>',
                                    '    <td width=91%>{NAMES}</td>',
                                    '	<input type="hidden" name="AZZYLR_DZ_NAMES" value="{IDS}"> ',
                                    '    <td width=9% style="text-align: right;"><img id="dz" style="width:22px;" src="images/delete01.png"/></td>',
                                    '  </tr>',
                                    '</table>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '安装工程',
                        height: '100%',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                height: 270,
                                layout: 'vbox',
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        items: [
                                            {
                                                xtype: 'panel',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'searchfield',
                                                        id:'installPlan_AZZYLR_AZGCFWS_JG',
                                                        height: 40,
                                                        width: '90%',
                                                        label: '服务商',
                                                        labelWidth: '42%',
                                                        name: '',
                                                        placeHolder: '请输入搜索关键字'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        id:'installPlan_AZZYLR_AZGCFWS_CXButton',
                                                        height: 41,
                                                        style: 'border:0;',
                                                        width: '10%',
                                                        iconCls: 'search',
                                                        text: ''
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '   ',
                                                labelWidth: '10%',
                                                id:'installPlan_AZZYLR_AZGCFWS_AZGCFWSGS',
                                                /*value: [
                                                    '  广东澳新电梯安装工程有限公司'
                                                ],*/
                                                readOnly: true
                                            },
                                            {//存放公司对应的ID
                                				xtype:'hiddenfield',
                                				id:'installPlan_AZZYLR_AZGCFWS_AZGCFWSGS_hidden',
                                			},
                                            {
                                                xtype: 'selectfield',
                                                id:'installPlanAZLR_AZRY',
                                                label: '安装人员',
                                                labelWidth: '40%',
                                                placeHolder: '请选择',
                                                usePicker: 'auto'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id:'installPlanAZLR_STARTIME',
                                               // dateFormat: 'Y-m-d',
                                                label: '计划开始',
                                                labelWidth: '40%',
                                                placeHolder: '请输入计划开始日期',
                                                readOnly:true,
                                                disabled:false,
                                                /*picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    doneButton: '确定',
                                                    cancelButton: '取消',
                                                },*/
                                                listeners:{
                                                	focus:function(){
                                                		initDate1('installPlanAZLR_STARTIME','计划开始');
                                                	}
                                                }
                                            },
                                            {
                                                xtype: 'textfield',
                                                id:'installPlanAZLR_ENDTIME',
                                                //dateFormat: 'Y-m-d',
                                                label: '计划结束',
                                                labelWidth: '40%',
                                                placeHolder: '请输入计划结束日期',
                                                readOnly:true,
                                                disabled:false,
                                                /*picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    doneButton: '确定',
                                                    cancelButton: '取消',
                                                },*/
                                                listeners:{
                                                	focus:function(){
                                                		initDate1('installPlanAZLR_ENDTIME','计划结束');
                                                	}
                                                }
                                            },
                                            {
                                                xtype: 'container',
                                                margin: '10 15',
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        id:'installPlanAZZY_AddAZRY',
                                                        text: '增加安装人员'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'list',
                                store:'InstallAZZYLRStoreFive',
                                id: 'installPlanAZZYLR_AZStore',
                                flex: 1,
                                itemTpl: [
                                    '<table width="100%" border="0" cellspacing="0" cellpadding="0">',
                                    '  <tr>',
                                    '    <td width=31%>{NAMES}</td>',
                                    '	<input type="hidden" name="AZZYLR_DZ_NAMES" value="{IDS}"> ',
                                    '      <td width=60% style="text-align: right;color:#666;">{TIME}</td>',
                                    '    <td width=9% style="text-align: right;"><img id="dz" style="width:22px;" src="images/delete01.png"/></td>',
                                    '  </tr>',
                                    '</table>'
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});