/*
 * File: app/view/InstallatoinTasksPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
/**
 * 安装计划
 * 2014-4-29 xcx
 */

Ext.define('HelcPDA.view.install.installplan.installPlan', {
    extend: 'Ext.Panel',
    id:'installplan_id',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.tab.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '安装计划',
                items: [
                    {
                        xtype: 'button',
                        text: '返回',
                        ui:'back',
                        id:'installplan_FH_Button',
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id:'installplan_TBAN_Button',
                        iconCls: 'arrow_down',
                    },
                    {
                        xtype: 'button',
                        iconCls: 'search',
                        id:'installplan_CXAN_Button',
                    },
                    {
                    	//动态的tcode;
        				xtype:'hiddenfield',
        				id:'installTcode',
        			},
        			{
        				//判断是从待办进还是安装项目进  1  2
        				xtype:'hiddenfield',
        				id:'intallplanDBXMnum',
        			},
        			{
        				//测试进入安装详细计划用 1
        				xtype:'hiddenfield',
        				id:'AZXXJH_JINRU_index',
        				value:0
        			},
        			{
        				//测试进入安装详细计划用 2
        				xtype:'hiddenfield',
        				id:'AZXXJH_JINRU_FLAG',
        				value:'false'
        			}
                ]
            },
            {
                xtype: 'tabpanel',
                flex: 1,
                id:'tabpanel_id',
                items: [
                    {
                        xtype: 'container',
                        title: '<div id="wjc"><div>',
                        id:'instalPlanWJCButton',
                        items: [
                            {
                                xtype: 'list',
                                id: 'instalPlanMylist',
                                store:'HelIntTasksAllStore',
                                height: '100%',
                                itemTpl: [
                                    '<table border=0 width=100%>',
                                    '    <tr height=20>',
                                    '        <td width=70%>',
                                    //font-size:22px;
                                    '            <span style="font-size:22px;">{ENGCONTRACT_NUMBER}</span>',
                                    '            <span style="color:#666">条数：{NUM}</span>',
                                    '        </td>',
                                    '    </tr>',
                                    '    <tr height=18>',
                                    '        <td><span style="color:#666">{CUSTOMER_NAME}</span></td>',
                                    '    </tr>',
                                    '    <tr height=18>',
                                    '        <td><span style="color:#666">未计划数:{WJH}</span></td>',
                                    '        <td><span style="color:#666">已计划数:{YJH}</span></td>',
                                    '    </tr>',
                                    '</table>'
                                ],
                                onItemDisclosure: true
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '<div id="zz"><div>',
                        id:'instalPlanZZButton',
                        items: [
                            {
                                xtype: 'list',
                                id: 'instalPlanMylistTwo',
                                store:'HelIntTasksAllStoreThree',
                                height: '100%',
                                itemTpl: [
                                          '<table border=0 width=100%>',
                                          '    <tr height=20>',
                                          '        <td width=70%>',
                                          '            <span style="font-size:22px;">{ENGCONTRACT_NUMBER}</span>',
                                          '            <span style="color:#666">条数：{NUM}</span>',
                                          '        </td>',
                                          '    </tr>',
                                          '    <tr height=18>',
                                          '        <td><span style="color:#666">{CUSTOMER_NAME}</span></td>',
                                          '    </tr>',
                                          '    <tr height=18>',
                                          '        <td><span style="color:#666">未计划数:{WJH}</span></td>',
                                          '        <td><span style="color:#666">已计划数:{YJH}</span></td>',
                                          '    </tr>',
                                          '</table>'
                                      ],
                                onItemDisclosure: true
                            }
                        ]
                    }
                ]
            }
        ]
    }

});

