/*
 * File: app/view/XTMyPanel33.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HELCSS.view.XTMyPanel33', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '报检详细信息',
                items: [
                    {
                        xtype: 'button',
                        ui: 'back',
                        text: '返回'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton5',
                        text: '保存'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton6',
                        text: '提交'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                flex: 1,
                items: [
                    {
                        xtype: 'container',
                        title: '查看数据',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '服务请求编号',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-914933251'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '受信时间',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '受信地盘',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '受信大楼',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '梯号',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '受信地址',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '工号',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '是否困人',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '受信内容',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '联系人姓名',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '联系人电话',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '所属司',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '所属站',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '预约时间',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '派工人员',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '主机型号',
                                                labelWidth: '40%',
                                                value: [
                                                    '1-F4Q70M'
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: '电源电流',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '上行（0%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '5.11'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '下行（0%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '1.8'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '上行（30%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '2.21'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '下行（30%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '1.03'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '上行（40%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '2.41'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '下行（40%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '0.11'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '上行（50%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '0.1'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '下行（50%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '3.324'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '上行（60%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '8.32'
                                                ],
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '下行（60%）',
                                                labelWidth: '40%',
                                                value: [
                                                    '22.97'
                                                ],
                                                readOnly: true
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '维护信息',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                flex: 1,
                                height: 600,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'datepickerfield',
                                                label: '报检日期',
                                                labelWidth: '40%',
                                                placeHolder: '请输入报检时间',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    doneButton: '完成',
                                                    cancelButton: '取消'
                                                }
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});