/*
 * File: app/store/Home_Unconfirmed_lsit.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcOA.store.yuyue.Home_Unconfirmed_lsit', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'Home_Unconfirmed_lsit',
        fields: [
            {
                name: 'title'
            },
            {
                name: 'company'
            },
            {
                name: 'date'
            },{
            	name: 'cacceptman'
            },{
            	name: 'jdr'
            },{
                name: 'address'
            },
            {
                name: 'rs'
            },
            {
                name: 'yijian'
            },{
            	name: 'peo1'
            },{
            	name: 'sex1'
            },{
            	name: 'job1'
            },{
            	name: 'peo2'
            },{
            	name: 'sex2'
            },{
            	name: 'job2'
            },{
            	name: 'peo3'
            },{
            	name: 'sex3'
            },{
            	name: 'job3'
            },{
            	name: 'FileNo'
            },{
            	name:'type'
            },{
            	name:'ccdate'
            },{
            	name:'yylx'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;

                if(!global.isWorklight()) {
                    // adapter取数
                    var url = '';
                    var userid = global.getUserId();
                    var adapterParm = {};

                    callPostAdapter(
                        url, adapterParm,
                        function(ret) {
                            me.setData(ret.data);
                            onSuccess();
                        },
                    onFailure);
                } else {
                    this.setData([
                        {
                            title : '标题',
                            company : '单位',
                            date : '2016-03-01'
                        },
                        {
                            title : '标题',
                            company : '单位',
                            date : '2016-03-01'
                        },
                        {
                            title : '标题',
                            company : '单位',
                            date : '2016-03-01'
                        },
                    ]);

                    onSuccess();
                }
    },

    updateDat: function(onSuccess, onFailure, parm) {

    },

    filteDat: function(parm) {

    }

});