/*
 * File: app/view/Director/ClueHandleDirector.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HelcPAD.view.OpportunityManagement.Director.ClueHandleDirector', {
    extend: 'Ext.form.Panel',
    id:'clueHandleDirector',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.FieldSet',
        'Ext.field.Number',
        'Ext.field.Toggle',
        'Ext.field.Select'
    ],

    config: {
      
        items: [
            {
            	id:'clueHandleDirector_id_toolbar',
                xtype: 'toolbar',
                docked: 'top',
                title: '线索处理',
                cls:'textf',
                items: [
                   /* {
                        xtype: 'button',
                        ui: 'back',
                        text: '',
                        id:'clueHandleDirector_FH',
                        text: '返回',
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        text: '执行',
                        id:'clueHandleDirector_ZX',
                    },*/
                    {
                    	//用于存放团队成员  
        				xtype:'hiddenfield',
        				id:'clueHandleDirector_TDCY',
        			},
        			{
                    	//用于存放线索跟踪人
        				xtype:'hiddenfield',
        				id:'clueHandleDirector_XSGZR',
        			},
        			
                ]
            },
            {
            	id:'clueHandleDirector_toolbar',
                xtype: 'toolbar',
                docked: 'top',
                //height: 85,
                layout: 'hbox',
                style: 'background:#EDEBF1;',
                /*html:'<div style="width=100%">'+
                		'<div class="anTwoDiv">'+
                			'<div class="kOne ysZhOne anOne" id="clueHandleDirector_SYY">'+SYB+'</div>'+
                			'<div class="kOne ysZhTwo anOne" id="clueHandleDirector_CZZX">操作执行</div>'+
                		'</div>'+
                		'<div class="anTwoDiv">'+
            				'<div class="kOne ysZhThree anOne" id="clueHandleDirector_GLSJ">关联商机</div>'+
            				'<div class="kOne ysZhFour anOne" id="clueHandleDirector_XSGZ">线索跟踪人</div>'+
            			'</div>'+
                	 '</div>',*/
            },
            
            {
                xtype: 'fieldset',
                cls:'textf',
                items: [
                    {
                    	id:'Clue_ID',
                    	name:'Id',
                        xtype: 'textfield',
                        label: '线索编号',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_LeadSource',
                    	name:'LeadSource',
                        xtype: 'textfield',
                        label: '线索来源',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_SubmitDate',
                    	name:'SubmitDate',
                        xtype: 'textfield',
                        label: '提交日期时间',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_RegistrationSequence',
                    	name:'RegistrationSequence',
                        xtype: 'textfield',
                        label: '报备顺序',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_AgentName',
                    	name:'AgentName',
                        xtype: 'textfield',
                        label: '经销商名称',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_RegistrationPerson',
                    	name:'RegistrationPerson',
                        xtype: 'textfield',
                        label: '报备人',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_ProjectName',
                    	name:'ProjectName',
                        xtype: 'textfield',
                        label: '项目名称',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_Account',
                    	name:'Account',
                        xtype: 'textfield',
                        label: ' 商机客户',//商机客户  选择
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                        required:true,
                    },
                    {
                    	id:'LeadFinalUser',
                    	name:'LeadFinalUser',
                        xtype: 'textfield',
                        label: '使用单位',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_ProjectArea',
                    	name:'ProjectArea',
                        xtype: 'textfield',
                        label: '区域',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_Province',
                    	name:'Province',
                        xtype: 'textfield',
                        label: '省/直辖市',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_City',
                    	name:'City',
                        xtype: 'textfield',
                        label: '市',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_County',
                    	name:'County',
                        xtype: 'textfield',
                        label: '区/县',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_StreetAddress',
                    	name:'StreetAddress',
                        xtype: 'textfield',
                        label: '商机地址',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                        required:true,
                    },
                    {
                    	id:'Clue_XHeight',
                    	name:'XHeight',
                    	xtype: 'numberfield',
                    	label: '定位坐标X',
                    	labelWidth: 155,
                    	width:'100%',
                    	readOnly: true,
                    },
                    {
                    	id:'Clue_YCoordinate',
                    	name:'YCoordinate',
                    	xtype: 'numberfield',
                    	label: '定位坐标Y',
                    	labelWidth: 155,
                    	width:'100%',
                    	readOnly: true,
                    },
                    {//*
                    	id:'Clue_opptyCategory',
                    	name:'LeadCategory',
                    	xtype:'textfield',
                    	label:'线索类型',
                    	width:'100%',
                    	labelWidth: 155,
                    	readOnly: true,
                    	hidden:true,
                    },
                    {//*
                    	id:'Clue_opptySubCategory',
                    	name:'LeadSubCategory',
                    	xtype:'textfield',
                    	label:'线索子类型',
                    	width:'100%',
                    	labelWidth:155,
                    	readOnly: true,
                    	hidden:true,
                    },
                    /*{
                        xtype: 'textfield',
                        label: '定位坐标',
                        labelWidth: 155,
                        value:'113.323,21.213',
                        width:'100%',
                    },*/
                    {
                    	id:'Clue_BuildingHeight',
                    	name:'BuildingHeight',
                        xtype: 'numberfield',
                        label: '建筑高度',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_BuildingLayer',
                    	name:'BuildingLayer',
                        xtype: 'numberfield',
                        label: '建筑层数',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_EvaluateElevatorQuantity',
                    	name:'EvaluateElevatorQuantity',
                        xtype: 'numberfield',
                        label: '预估直梯台数',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_EvaluateEscalatorQuantity',
                    	name:'EvaluateEscalatorQuantity',
                        xtype: 'numberfield',
                        label: '预估扶梯台数',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {//*
                    	id:'Clue_PredictSignYear',
                    	name:'PredictSignYear',
                    	xtype:'textfield',
                    	label:'预计签约年',
                    	width:'100%',
                    	labelWidth: 155,
                    	readOnly: true,
                    	hidden:true,
                    },
                    {//*
                    	id:'Clue_PredictSignMonth',
                    	name:'PredictSignMonth',
                    	xtype:'textfield',
                    	label:'预计签约月',
                    	width:'100%',
                        labelWidth:155,
                        readOnly: true,
                    	hidden:true,
                    },
                    {//*
                    	id:'Clue_DealWithTime',
                    	name:'HandleDate',
                        xtype: 'textfield',
                        label: '线索处理时间',
                        width:'100%',
                        labelWidth:155,
                        readOnly: true,
                    	hidden:true,
                    },
                    {//*
                    	id:'Clue_supplierStatus',
                    	name:'AgentPerformanceStatus',
                        xtype: 'textfield',
                        label: '经销商状态',
                        width:'100%',
                        labelWidth:155,
                        readOnly: true,
                    	hidden:true,
                    },
                    {//*
                    	id:'Clue_taskAchieve',
                    	name:'PerformanceShared',
                        xtype: 'textfield',
                        label: '任务业绩',
                        width:'100%',
                        labelWidth:155,
                        readOnly: true,
                    	hidden:true,
                    },
                    {//*
                    	id:'Clue_achieveNum',
                    	name:'PerformanceCountCal',
                        xtype: 'textfield',
                        label: '业绩台量',
                        width:'100%',
                        labelWidth:155,
                        readOnly: true,
                    	hidden:true,
                    },
                    {
                    	id:'Clue_BigCustomer',
                    	name:'BigCustomer',
                        xtype: 'textfield',
                        label: '大客户名称',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_AccountKaNumber',
                    	name:'AccountKaNumber',
                        xtype: 'textfield',
                        label: '大客户编号',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_LeadMajorProjet',
                    	name:'LeadMajorProjet',
                        xtype: 'togglefield',
                        //centered: true,
                        label: '大项目关注',
                        labelWidth: 170,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_LeadImportDemand',
                    	name:'LeadImportDemand',
                        xtype: 'togglefield',
                        //centered: true,
                        label: '进口大部件需求',
                        labelWidth: 170,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_Description',
                    	name:'Description',
                        xtype: 'textfield',
                        label: '客户需求',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_LeadStatus',
                    	name:'LeadStatus',
                        xtype: 'textfield',
                        label: '线索状态',
                        labelWidth: 155,
                        //centered: true,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_OpptyStatus',
                    	name:'OpptyStatus',
                        xtype: 'textfield',
                        label: '商机状态',
                        labelWidth: 155,
                        width:'100%',
                        readOnly:true,
                    },
                    {
                    	id:'Clue_GLSJ',
                    	name:'OpptyNumber',
                        xtype: 'textfield',
                        style: 'float: left',
                        width: '100%',
                        label: '关联商机',
                        labelWidth: 155,
                        readOnly:true,
                        hidden:true,
                    },
                    {
                    	id:'Clue_OpptyId',
                    	name:'OpptyId',
                        xtype: 'textfield',
                        style: 'float: left',
                        width: '100%',
                        label: '关联商机ID',
                        labelWidth: 155,
                        readOnly:true,
                        hidden:true,
                    },
                    /*{
                    	id:'Clue_GLSJ_XZ',
                        xtype: 'button',
                        margin: '10 5 10 0',
                        maxWidth: 70,
                        minWidth: 50,
                        padding: '',
                        style: 'float: left',
                        width: '25%',
                        text: '选择'
                    },*/
                    {
                    	id:'Clue_XSGZR',
                        xtype: 'textfield',
                        style: 'float: left',
                        width: '100%',
                        label: '线索跟踪人',
                        labelWidth: 155,
                        readOnly:true,
                        hidden:true,
                    },
                    /*{
                    	id:'Clue_XSGZR_XZ',
                        xtype: 'button',
                        margin: '10 5 10 0',
                        maxWidth: 70,
                        minWidth: 50,
                        padding: '',
                        style: 'float: left',
                        width: 70,
                        text: '选择'
                    },*/
                    //2015-12-08
                    /*{
                    	id:'Clue_TDCY',
                        xtype: 'textfield',
                        style: 'float: left',
                        width: '76%',
                        label: '团队成员',
                        labelWidth: 155,
                        readOnly:true,
                        value:'',
                    },
                    {
                    	id:'Clue_TDCY_XZ',
                        xtype: 'button',
                        margin: '10 5 10 0',
                        maxWidth: 70,
                        minWidth: 50,
                        padding: '',
                        style: 'float: left',
                        width: 70,
                        text: '选择'
                    },*/
                    {//主管操作就是审批操作
                    	id:'Clue_ApproveOperate',
                    	name:'ApproveOperate',
                        xtype: 'selectfield',
                        style: 'float: left',
                        label: '主管操作',
                        labelWidth: 155,
                        width:'100%',
                        hidden:true,
                    },
                    {
                    	id:'Clue_ManagerRejectComments',
                    	name:'ManagerRejectComments',
                        xtype: 'selectfield',
                        style: 'float: left',
                        label: '驳回意见',
                        labelWidth: 155,
                        width:'100%',
                    }
                    
                ]
            }
        ]
    },

	//初始化
	initialize:function(){
	},
});