/*
 * File: app/view/FaultHandlingInputPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/**
 * 服务请求录入页面 2014-4-18 xcx
 */

Ext.define('HelcPDA.view.fault.FaultHandlingInputPanel', {
    extend: 'Ext.Panel',
    id:'faultFHIP',
    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.Label',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.field.Search'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '服务请求录入',
                items: [
                    {
                        xtype: 'button',
                        id:'FaultFHIPReturnButton',
                        ui: 'back',
                        text: '返回'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                    	//客户ID
        				xtype:'hiddenfield',
        				id:'ACCOUNT_ID',
        			},
        			{
                    	//故障工号 
        				xtype:'hiddenfield',
        				id:'ASSET_ID',
        			},
        			{
                    	//受信故障 
        				xtype:'hiddenfield',
        				id:'gz',
        			}
                ]
            },
            {
                xtype: 'formpanel',
                flex: 1,
                height: 600,
                items: [
                    {
                        xtype: 'fieldset',
                        title: '   查询条件(可填)',
                        items: [
                            {
                                xtype: 'textfield',
                                label: '工号',
                                id:'FaultFHIP_GH',
                                labelWidth: '40%',
                                placeHolder: '请输入工号'
                            },
                            {
                                xtype: 'textfield',
                                label: '受信地盘',
                                id:'FaultFHIP_SXDP',
                                labelWidth: '40%',
                                placeHolder: '请输入受信地盘'
                            },
                            {
                                xtype: 'textfield',
                                label: '受信大楼',
                                id:'FaultFHIP_SXDL',
                                labelWidth: '40%',
                                placeHolder: '请输入受信大楼'
                            },
                            {
                                xtype: 'textfield',
                                label: '受信地址',
                                id:'FaultFHIP_SXDZ',
                                labelWidth: '40%',
                                placeHolder: '请输入受信地址'
                            },
                            {
                                xtype: 'panel',
                                layout: {
                                    type: 'hbox',
                                    align: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'button',
                                        id:'FaultFHIPQueryButton',
                                        margin: '15 0',
                                        width: '90%',
                                        text: '查询'
                                    },
                                    {
                                        xtype: 'spacer'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        cls: 'm-label-prompt',
                        height: 66,
                        html: '操作提示：<br>1.先选择对应的查询条件(站、片、组)。<br>2.点击\'查询\'按钮。<br>3.找出对应动转派人员，再点击\'提交\'按钮转派故障单。',
                        margin: '5 auto 0 auto',
                        width: '96%'
                    },
                    {
                        xtype: 'fieldset',
                        title: '其它输入项',
                        items: [
                            {
                                xtype: 'textfield',
                                component: {
                                    xtype: 'input',
                                    type: 'text',
                                    fastFocus: true
                                },
                                label: '所属公司',
                                id:'FaultFHIPCompanyName',
                                labelWidth: '40%',
                                /*value: [
                                    '广州分公司'
                                ],*/
                                placeHolder: '',
                                readOnly: true
                            },
                            {
                                xtype: 'selectfield',
                                label: '所属站',
                                id:'FaultFHIPStation',
                                labelWidth: '40%',
                                placeHolder: '请选择所属站',
                                valueField:'STATION_CODE',//提交的值,先 这样后期修改
                                displayField:'STATION_NAME',
                                store:'HelSblStationStore',
                                /*options: [
                                    {
                                        text: '请选择',
                                        value: '请选择'
                                    },
                                    {
                                        text: '海珠站',
                                        value: '海珠站'
                                    },
                                    {
                                        text: '花都站',
                                        value: '花都站'
                                    },
                                    {
                                        text: '黄埔站',
                                        value: '黄埔站'
                                    }
                                ],*/
                                usePicker: 'auto'
                            },
                            {
                                xtype: 'textfield',
                                label: '受信内容',
                                id:'FaultFHIP_SXNR',
                                labelWidth: '40%',
                                placeHolder: '请输入受信内容',
                                readOnly: false
                            },
                           /* {
                                xtype: 'datepickerfield',
                                label: '受信时间',
                                id:'FaultFHIP_SXSJ',
                                labelWidth: '40%',
                                placeHolder: '请输入受信时间',
                                picker: {
                                    slotOrder: [
                                        'year',
                                        'month',
                                        'day'
                                    ],
                                    doneButton: '完成',
                                    cancelButton: '取消'
                                },
                                value:new Date(),
                                dateFormat:'Y/m/d',
                            },*/
                            {   xtype:'textfield',
                            	label: '受信时间',
                                placeHolder: '请输入受信时间',
                                labelWidth: '40%',
                                id:'FaultFHIP_SXSJ',
                                readOnly:true,
                                listeners:{
                                	focus:function(){
                            			need_text_id='FaultFHIP_SXSJ';
                            			initDate(Ext.getCmp('FaultFHIP_SXSJ').getValue(),'受信时间');
                            			picker_show.show();
                                	}
                                }
                            },
                            /*{
                                xtype: 'datepickerfield',
                                label: '发生时间',
                                id:'FaultFHIP_FSSJ',
                                labelWidth: '40%',
                                placeHolder: '请输入发生时间',
                                picker: {
                                    slotOrder: [
                                        'year',
                                        'month',
                                        'day'
                                    ],
                                    doneButton: '完成',
                                    cancelButton: '取消'
                                }
                            },*/
                            {   xtype:'textfield',
                            	label: '发生时间',
                                placeHolder: '请输入发生时间',
                                labelWidth: '40%',
                                id:'FaultFHIP_FSSJ',
                                readOnly:true,
                                listeners:{
                                	focus:function(){
                                		need_text_id='FaultFHIP_FSSJ';
                            			initDate(Ext.getCmp('FaultFHIP_FSSJ').getValue(),'发生时间');
                            			picker_show.show();
                                	}
                                }
                            },
                            {
                                xtype: 'textfield',
                                label: '联系人姓名',
                                id:'FaultFHIP_LXRXM',
                                labelWidth: '40%',
                                placeHolder: '请输入联系人姓名',
                                readOnly: false
                            },
                            {
                                xtype: 'textfield',
                                label: '联系人电话',
                                id:'FaultFHIP_LXRDH',
                                labelWidth: '40%',
                                placeHolder: '请输入联系人电话',
                                readOnly: false
                            },
                            {
                                xtype: 'selectfield',
                                label: '是否困人',
                                id:'FaultFHIP_SFKR',
                                labelWidth: '40%',
                                placeHolder: '请选择',
                                options: [
                                    {
                                        text: '请选择',
                                        value: '请选择'
                                    },
                                    {
                                        text: '否',
                                        value: 'No'
                                    },
                                    {
                                        text: '是',
                                        value: 'Yes'
                                    }
                                ],
                                usePicker: 'auto'
                            },
                            {
                                xtype: 'selectfield',
                                label: '故障状态',
                                id:'FaultFHIP_SXGZZT',
                                labelWidth: '40%',
                                placeHolder: '请选择',
                                valueField:'LANGUAGE_CODE',//提交的值,先 这样后期修改
                                displayField:'STATUS',
                                store:'HelHotlineFaultStatusStore',
                                /*options: [
                                    {
                                        text: '请选择',
                                        value: '请选择'
                                    },
                                    {
                                        text: '不开门',
                                        value: '不开门'
                                    },
                                    {
                                        text: '开门后不启动(不运行)',
                                        value: '开门后不启动(不运行)'
                                    },
                                    {
                                        text: '门不能完全关闭',
                                        value: '门不能完全关闭'
                                    }
                                ],*/
                                usePicker: 'auto'
                            },
                            {
                                xtype: 'searchfield',
                                label: '客户',
                                id:'FaultFHIP_KH',
                                labelWidth: '40%',
                                placeHolder: '请输入客户名',
                            },
                            {
                                xtype: 'panel',
                                layout: {
                                    type: 'hbox',
                                    align: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'button',
                                        id:'FaultAccntNameButton',
                                        margin: '15 0',
                                        width: '90%',
                                        text: '查询'
                                    },
                                    {
                                        xtype: 'spacer'
                                    }
                                ]
                            },
                            /*{
                                xtype: 'datepickerfield',
                                label: '预约时间',
                                id:'FaultFHIP_YYSJ',
                                labelWidth: '40%',
                                placeHolder: '请输入预约时间',
                                picker: {
                                    slotOrder: [
                                        'year',
                                        'month',
                                        'day'
                                    ],
                                    doneButton: '完成',
                                    cancelButton: '取消'
                                }
                            },*/
                            {   xtype:'textfield',
                            	label: '预约时间',
                                placeHolder: '请输入预约时间',
                                labelWidth: '40%',
                                id:'FaultFHIP_YYSJ',
                                readOnly:true,
                                listeners:{
                                	focus:function(){
                                		need_text_id='FaultFHIP_YYSJ';
                            			initDate(Ext.getCmp('FaultFHIP_YYSJ').getValue(),'预约时间');
                            			picker_show.show();
                                	}
                                }
                            },
                            {
                                xtype: 'selectfield',
                                label: '派工人员',
                                id:'FaultFHIPPersonName',
                                labelWidth: '40%',
                                placeHolder: '请选择',
                               /* options: [
                                    {
                                        text: '请选择',
                                        value: '请选择'
                                    },
                                    {
                                        text: '正常',
                                        value: '正常'
                                    },
                                    {
                                        text: '异常',
                                        value: '异常'
                                    }
                                ],*/
                                usePicker: 'auto'
                            },
                            {
                                xtype: 'panel',
                                layout: {
                                    type: 'hbox',
                                    align: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'button',
                                        id:'FaultFHIPSubmitButton',
                                        margin: '15 0',
                                        width: '90%',
                                        text: '提交'
                                    },
                                    {
                                        xtype: 'spacer'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    },
    

});